window.ESSAY_TEXT = {
  "id": "marcus-aurelius-book-2",
  "title": "Meditations, Book II",
  "titleOriginal": null,
  "author": "Marcus Aurelius",
  "authorNative": null,
  "year": "c. 170",
  "language": "en",
  "kind": "selection",
  "why": "The emperor's private notes to himself, never meant for readers. Book II opens with the busy-body/ungrateful-people morning rehearsal and stays essay-length. George Long's 1862 translation is deliberately plain.",
  "themes": [
    "morning",
    "mortality",
    "self-command"
  ],
  "rightsNote": "George Long translation, 1862 (eBook 15877). Public domain everywhere. Note: eBook 2680 is the older Casaubon translation, not used here.",
  "sourceLabel": "Project Gutenberg eBook 15877 (George Long)",
  "sourcePage": "https://www.gutenberg.org/ebooks/15877",
  "provenance": "fetched (scripts/build_essays_sources.py; local mirror: 15877-8.txt)",
  "generated": "2026-07-11",
  "paragraphs": [
    "Begin the morning by saying to thyself, I shall meet with the busybody,\nthe ungrateful, arrogant, deceitful, envious, unsocial. All these things\nhappen to them by reason of their ignorance of what is good and evil.\nBut I who have seen the nature of the good that it is beautiful, and of\nthe bad that it is ugly, and the nature of him who does wrong, that it\nis akin to me; not [only] of the same blood or seed, but that it\nparticipates in [the same] intelligence and [the same] portion of the\ndivinity, I can neither be injured by any of them, for no one can fix on\nme what is ugly, nor can I be angry with my kinsman, nor hate him. For\nwe are made for co-operation, like feet, like hands, like eyelids, like\nthe rows of the upper and lower teeth.[A] To act against one another,\nthen, is contrary to nature; and it is acting against one another to be\nvexed and to turn away.",
    "[A] Xenophon, Mem. ii. 3. 18.",
    "2. Whatever this is that I am, it is a little flesh and breath, and the\nruling part. Throw away thy books; no longer distract thyself: it is not\nallowed; but as if thou wast now dying, despise the flesh; it is blood\nand bones and network, a contexture of nerves, veins, and arteries. See\nthe breath also, what kind of a thing it is; air, and not always the\nsame, but every moment sent out and again sucked in. The third, then, is\nthe ruling part; consider thus: Thou art an old man; no longer let this\nbe a slave, no longer be pulled by the strings like a puppet to unsocial\nmovements, no longer be either dissatisfied with thy present lot, or\nshrink from the future.",
    "3. All that is from the gods is full of providence. That which is from\nfortune is not separated from nature or without an interweaving and\ninvolution with the things which are ordered by providence. From thence\nall things flow; and there is besides necessity, and that which is for\nthe advantage of the whole universe, of which thou art a part. But that\nis good for every part of nature which the nature of the whole brings,\nand what serves to maintain this nature. Now the universe is preserved,\nas by the changes of the elements so by the changes of things compounded\nof the elements. Let these principles be enough for thee; let them\nalways be fixed opinions. But cast away the thirst after books, that\nthou mayest not die murmuring, but cheerfully, truly, and from thy heart\nthankful to the gods.",
    "4. Remember how long thou hast been putting off these things, and how\noften thou hast received an opportunity from the gods, and yet dost not\nuse it. Thou must now at last perceive of what universe thou art a\npart, and of what administrator of the universe thy existence is an\nefflux, and that a limit of time is fixed for thee, which if thou dost\nnot use for clearing away the clouds from thy mind, it will go and thou\nwilt go, and it will never return.",
    "5. Every moment think steadily as a Roman and a man to do what thou hast\nin hand with perfect and simple dignity, and feeling of affection, and\nfreedom, and justice, and to give thyself relief from all other\nthoughts. And thou wilt give thyself relief if thou doest every act of\nthy life as if it were the last, laying aside all carelessness and\npassionate aversion from the commands of reason, and all hypocrisy, and\nself-love, and discontent with the portion which has been given to thee.\nThou seest how few the things are, the which if a man lays hold of, he\nis able to live a life which flows in quiet, and is like the existence\nof the gods; for the gods on their part will require nothing more from\nhim who observes these things.",
    "6. Do wrong[A] to thyself, do wrong to thyself, my soul; but thou wilt\nno longer have the opportunity of honoring thyself. Every man's life is\nsufficient.+ But thine is nearly finished, though thy soul reverences\nnot itself, but places thy felicity in the souls of others.",
    "[A] Perhaps it should be, \"thou art doing violence to thyself.\"\n[Greek: hybrizeis] not [Greek: hybrize].",
    "7. Do the things external which fall upon thee distract thee? Give\nthyself time to learn something new and good, and cease to be whirled\naround. But then thou must also avoid being carried about the other way;\nfor those too are triflers who have wearied themselves in life by their\nactivity, and yet have no object to which to direct every movement, and,\nin a word, all their thoughts.",
    "8. Through not observing what is in the mind of another a man has seldom\nbeen seen to be unhappy; but those who do not observe the movements of\ntheir own minds must of necessity be unhappy.",
    "9. This thou must always bear in mind, what is the nature of the whole,\nand what is my nature, and how this is related to that, and what kind of\na part it is of what kind of a whole, and that there is no one who\nhinders thee from always doing and saying the things which are according\nto the nature of which thou art a part.",
    "10. Theophrastus, in his comparison of bad acts--such a comparison as\none would make in accordance with the common notions of mankind--says,\nlike a true philosopher, that the offenses which are committed through\ndesire are more blamable than those which are committed through anger.\nFor he who is excited by anger seems to turn away from reason with a\ncertain pain and unconscious contraction; but he who offends through\ndesire, being overpowered by pleasure, seems to be in a manner more\nintemperate and more womanish in his offences. Rightly, then, and in a\nway worthy of philosophy, he said that the offence which is committed\nwith pleasure is more blamable than that which is committed with pain;\nand on the whole the one is more like a person who has been first\nwronged and through pain is compelled to be angry, but the other is\nmoved by his own impulse to do wrong, being carried towards doing\nsomething by desire.",
    "11. Since it is possible[A] that thou mayest depart from life this very\nmoment, regulate every act and thought accordingly.[B] But to go away\nfrom among men, if there are gods, is not a thing to be afraid of, for\nthe gods will not involve thee in evil; but if indeed they do not exist,\nor if they have no concern about human affairs, what is it to me to live\nin a universe devoid of gods or devoid of providence? But in truth they\ndo exist, and they do care for human things, and they have put all the\nmeans in man's power to enable him not to fall into real evils. And as\nto the rest, if there was anything evil, they would have provided for\nthis also, that it should be altogether in a man's power not to fall\ninto it. Now that which does not make a man worse, how can it make a\nman's life worse? But neither through ignorance, nor--having the\nknowledge but not the power to guard against or correct these things, is\nit possible that the nature of the universe has overlooked them; nor is\nit possible that it has made so great a mistake, either through want of\npower or want of skill, that good and evil should happen\nindiscriminately to the good and the bad. But death certainly, and life,\nhonor and dishonor, pain and pleasure,--all these things equally happen\nto good men and bad, being things which make us neither better nor\nworse. Therefore they are neither good nor evil.",
    "[A] Or it may mean, \"since it is in thy power to depart;\" which\ngives a meaning somewhat different.",
    "[B] See Cicero, Tuscul., i. 49.",
    "12. How quickly all things disappear,--in the universe the bodies\nthemselves, but in time the remembrance of them. What is the nature of\nall sensible things, and particularly those which attract with the bait\nof pleasure or terrify by pain, or are noised abroad by vapory fame; how\nworthless, and contemptible, and sordid, and perishable, and dead they\nare,--all this it is the part of the intellectual faculty to observe. To\nobserve too who these are whose opinions and voices give reputation;\nwhat death is, and the fact that, if a man looks at it in itself, and by\nthe abstractive power of reflection resolves into their parts all the\nthings which present themselves to the imagination in it, he will then\nconsider it to be nothing else than an operation of nature; and if any\none is afraid of an operation of nature, he is a child. This, however,\nis not only an operation of nature, but it is also a thing which\nconduces to the purposes of nature. To observe too how man comes near to\nthe Deity, and by what part of him, and when this part of man is so\ndisposed+ (vi. 28).",
    "13. Nothing is more wretched than a man who traverses everything in a\nround, and pries into the things beneath the earth, as the poet[A] says,\nand seeks by conjecture what is in the minds of his neighbors, without\nperceiving that it is sufficient to attend to the daemon within him, and\nto reverence it sincerely. And reverence of the daemon consists in\nkeeping it pure from passion and thoughtlessness, and dissatisfaction\nwith what comes from gods and men. For the things from the gods merit\nveneration for their excellence; and the things from men should be dear\nto us by reason of kinship; and sometimes even, in a manner, they move\nour pity by reason of men's ignorance of good and bad; this defect being\nnot less than that which deprives us of the power of distinguishing\nthings that are white and black.",
    "[A] Pindar, in the Theaetetus of Plato. See xi. 1.",
    "14. Though thou shouldest be going to live three thousand years and as\nmany times ten thousand years, still remember that no man loses any\nother life than this which he now lives, nor lives any other than this\nwhich he now loses. The longest and shortest are thus brought to the\nsame. For the present is the same to all, though that which perish is\nnot the same;+[A] and so that which is lost appears to be a mere\nmoment. For a man cannot lose either the past or the future: for what a\nman has not, how can any one take this from him? These two things then\nthou must bear in mind; the one, that all things from eternity are of\nlike forms and come round in a circle, and that it makes no difference\nwhether a man shall see the same things during a hundred years, or two\nhundred, or an infinite time; and the second, that the longest liver and\nhe who will die soonest lose just the same. For the present is the only\nthing of which a man can be deprived, if it is true that this is the\nonly thing which he has, and that a man cannot lose a thing if he has it\nnot.",
    "[A] See Gataker's note.",
    "15. Remember that all is opinion. For what was said by the Cynic Monimus\nis manifest: and manifest too is the use of what was said, if a man\nreceives what may be got out of it as far as it is true.",
    "16. The soul of man does violence to itself, first of all, when it\nbecomes an abscess, and, as it were, a tumor on the universe, so far as\nit can. For to be vexed at anything which happens is a separation of\nourselves from nature, in some part of which the natures of all other\nthings are contained. In the next place, the soul does violence to\nitself when it turns away from any man, or even moves towards him with\nthe intention of injuring, such as are the souls of those who are angry.\nIn the third place, the soul does violence to itself when it is\noverpowered by pleasure or by pain. Fourthly, when it plays a part, and\ndoes or says anything insincerely and untruly. Fifthly, when it allows\nany act of its own and any movement to be without an aim, and does\nanything thoughtlessly and without considering what it is, it being\nright that even the smallest things be done with reference to an end;\nand the end of rational animals is to follow the reason and the law of\nthe most ancient city and polity.",
    "17. Of human life the time is a point, and the substance is in a flux,\nand the perception dull, and the composition of the whole body subject\nto putrefaction, and the soul a whirl, and fortune hard to divine, and\nfame a thing devoid of judgment. And, to say all in a word, everything\nwhich belongs to the body is a stream, and what belongs to the soul is a\ndream and vapor, and life is a warfare and a stranger's sojourn, and\nafter fame is oblivion. What then is that which is able to conduct a\nman? One thing, and only one, philosophy. But this consists in keeping\nthe daemon within a man free from violence and unharmed, superior to\npains and pleasures, doing nothing without a purpose, nor yet falsely\nand with hypocrisy, not feeling the need of another man's doing or not\ndoing anything; and besides, accepting all that happens, and all that\nis allotted, as coming from thence, wherever it is, from whence he\nhimself came; and, finally, waiting for death with a cheerful mind, as\nbeing nothing else than a dissolution of the elements of which every\nliving being is compounded. But if there is no harm to the elements\nthemselves in each continually changing into another, why should a man\nhave any apprehension about the change and dissolution of all the\nelements? For it is according to nature, and nothing is evil which is\naccording to nature.",
    "This in Carnuntum.[A]",
    "[A] Carnuntum was a town of Pannonia, on the south side of the\nDanube, about thirty miles east of Vindobona (Vienna).\nOrosius (vii. 15) and Eutropius (viii. 13) say that Antoninus\nremained three years at Carmuntum during his war with the\nMarcomanni."
  ],
  "guideIntro": [
    "Book II is a morning discipline written by an emperor on campaign: anticipate difficult people, reduce the self to its mortal components, and return attention to the action immediately yours."
  ],
  "notes": {
    "1": "The opening is often flattened into “ignore toxic people.” Marcus instead establishes kinship: their failures come from mistaken judgments, and harming them would violate the social nature he shares with them.",
    "13": "The repeated reminders of death narrow the field of obligation. Mortality is used to remove performance, resentment, and delay—not to make present conduct meaningless.",
    "17": "Prying into other minds is contrasted with attending to one's own governing reason. The target is speculative moral surveillance: guessing motives instead of doing the next just act."
  },
  "audio": {}
};
