window.ESSAY_TEXT = {
  "id": "okakura-cup-of-humanity",
  "title": "The Cup of Humanity (The Book of Tea, I)",
  "titleOriginal": null,
  "author": "Okakura Kakuzo",
  "authorNative": null,
  "year": 1906,
  "language": "en",
  "kind": "chapter",
  "why": "Written directly in English by a Japanese curator explaining Asia to the West on his own terms: Teaism as the art of finding beauty inside ordinary daily life. Bridge into the Japanese aesthetics shelf.",
  "themes": [
    "aesthetics",
    "east-west",
    "everyday-ritual"
  ],
  "rightsNote": "Published 1906 in English; public domain everywhere.",
  "sourceLabel": "Project Gutenberg eBook 769",
  "sourcePage": "https://www.gutenberg.org/ebooks/769",
  "provenance": "fetched (scripts/build_essays_sources.py; local mirror: 769.txt)",
  "generated": "2026-07-11",
  "paragraphs": [
    "The Cup of Humanity",
    "Tea began as a medicine and grew into a beverage. In China, in the\neighth century, it entered the realm of poetry as one of the polite\namusements. The fifteenth century saw Japan ennoble it into a religion\nof aestheticism--Teaism. Teaism is a cult founded on the adoration\nof the beautiful among the sordid facts of everyday existence. It\ninculcates purity and harmony, the mystery of mutual charity, the\nromanticism of the social order. It is essentially a worship of the\nImperfect, as it is a tender attempt to accomplish something possible in\nthis impossible thing we know as life.",
    "The Philosophy of Tea is not mere aestheticism in the ordinary\nacceptance of the term, for it expresses conjointly with ethics and\nreligion our whole point of view about man and nature. It is hygiene,\nfor it enforces cleanliness; it is economics, for it shows comfort in\nsimplicity rather than in the complex and costly; it is moral geometry,\ninasmuch as it defines our sense of proportion to the universe. It\nrepresents the true spirit of Eastern democracy by making all its\nvotaries aristocrats in taste.",
    "The long isolation of Japan from the rest of the world, so conducive to\nintrospection, has been highly favourable to the development of\nTeaism. Our home and habits, costume and cuisine, porcelain, lacquer,\npainting--our very literature--all have been subject to its influence.\nNo student of Japanese culture could ever ignore its presence. It has\npermeated the elegance of noble boudoirs, and entered the abode of\nthe humble. Our peasants have learned to arrange flowers, our meanest\nlabourer to offer his salutation to the rocks and waters. In our\ncommon parlance we speak of the man \"with no tea\" in him, when he is\ninsusceptible to the serio-comic interests of the personal drama.\nAgain we stigmatise the untamed aesthete who, regardless of the mundane\ntragedy, runs riot in the springtide of emancipated emotions, as one\n\"with too much tea\" in him.",
    "The outsider may indeed wonder at this seeming much ado about nothing.\nWhat a tempest in a tea-cup! he will say. But when we consider how small\nafter all the cup of human enjoyment is, how soon overflowed with tears,\nhow easily drained to the dregs in our quenchless thirst for infinity,\nwe shall not blame ourselves for making so much of the tea-cup. Mankind\nhas done worse. In the worship of Bacchus, we have sacrificed too\nfreely; and we have even transfigured the gory image of Mars. Why not\nconsecrate ourselves to the queen of the Camelias, and revel in the warm\nstream of sympathy that flows from her altar? In the liquid amber within\nthe ivory-porcelain, the initiated may touch the sweet reticence of\nConfucius, the piquancy of Laotse, and the ethereal aroma of Sakyamuni\nhimself.",
    "Those who cannot feel the littleness of great things in themselves are\napt to overlook the greatness of little things in others. The average\nWesterner, in his sleek complacency, will see in the tea ceremony but\nanother instance of the thousand and one oddities which constitute the\nquaintness and childishness of the East to him. He was wont to regard\nJapan as barbarous while she indulged in the gentle arts of peace: he\ncalls her civilised since she began to commit wholesale slaughter on\nManchurian battlefields. Much comment has been given lately to the Code\nof the Samurai,--the Art of Death which makes our soldiers exult in\nself-sacrifice; but scarcely any attention has been drawn to Teaism,\nwhich represents so much of our Art of Life. Fain would we remain\nbarbarians, if our claim to civilisation were to be based on the\ngruesome glory of war. Fain would we await the time when due respect\nshall be paid to our art and ideals.",
    "When will the West understand, or try to understand, the East? We\nAsiatics are often appalled by the curious web of facts and fancies\nwhich has been woven concerning us. We are pictured as living on the\nperfume of the lotus, if not on mice and cockroaches. It is either\nimpotent fanaticism or else abject voluptuousness. Indian spirituality\nhas been derided as ignorance, Chinese sobriety as stupidity, Japanese\npatriotism as the result of fatalism. It has been said that we are less\nsensible to pain and wounds on account of the callousness of our nervous\norganisation!",
    "Why not amuse yourselves at our expense? Asia returns the compliment.\nThere would be further food for merriment if you were to know all\nthat we have imagined and written about you. All the glamour of the\nperspective is there, all the unconscious homage of wonder, all the\nsilent resentment of the new and undefined. You have been loaded with\nvirtues too refined to be envied, and accused of crimes too\npicturesque to be condemned. Our writers in the past--the wise men who\nknew--informed us that you had bushy tails somewhere hidden in your\ngarments, and often dined off a fricassee of newborn babes! Nay, we had\nsomething worse against you: we used to think you the most impracticable\npeople on the earth, for you were said to preach what you never\npracticed.",
    "Such misconceptions are fast vanishing amongst us. Commerce has forced\nthe European tongues on many an Eastern port. Asiatic youths are\nflocking to Western colleges for the equipment of modern education.\nOur insight does not penetrate your culture deeply, but at least we are\nwilling to learn. Some of my compatriots have adopted too much of\nyour customs and too much of your etiquette, in the delusion that the\nacquisition of stiff collars and tall silk hats comprised the attainment\nof your civilisation. Pathetic and deplorable as such affectations\nare, they evince our willingness to approach the West on our knees.\nUnfortunately the Western attitude is unfavourable to the understanding\nof the East. The Christian missionary goes to impart, but not to\nreceive. Your information is based on the meagre translations of our\nimmense literature, if not on the unreliable anecdotes of passing\ntravellers. It is rarely that the chivalrous pen of a Lafcadio Hearn\nor that of the author of \"The Web of Indian Life\" enlivens the Oriental\ndarkness with the torch of our own sentiments.",
    "Perhaps I betray my own ignorance of the Tea Cult by being so outspoken.\nIts very spirit of politeness exacts that you say what you are expected\nto say, and no more. But I am not to be a polite Teaist. So much harm\nhas been done already by the mutual misunderstanding of the New World\nand the Old, that one need not apologise for contributing his tithe\nto the furtherance of a better understanding. The beginning of the\ntwentieth century would have been spared the spectacle of sanguinary\nwarfare if Russia had condescended to know Japan better. What dire\nconsequences to humanity lie in the contemptuous ignoring of Eastern\nproblems! European imperialism, which does not disdain to raise the\nabsurd cry of the Yellow Peril, fails to realise that Asia may also\nawaken to the cruel sense of the White Disaster. You may laugh at us for\nhaving \"too much tea,\" but may we not suspect that you of the West have\n\"no tea\" in your constitution?",
    "Let us stop the continents from hurling epigrams at each other, and be\nsadder if not wiser by the mutual gain of half a hemisphere. We have\ndeveloped along different lines, but there is no reason why one should\nnot supplement the other. You have gained expansion at the cost\nof restlessness; we have created a harmony which is weak against\naggression. Will you believe it?--the East is better off in some\nrespects than the West!",
    "Strangely enough humanity has so far met in the tea-cup. It is the only\nAsiatic ceremonial which commands universal esteem. The white man has\nscoffed at our religion and our morals, but has accepted the brown\nbeverage without hesitation. The afternoon tea is now an important\nfunction in Western society. In the delicate clatter of trays and\nsaucers, in the soft rustle of feminine hospitality, in the common\ncatechism about cream and sugar, we know that the Worship of Tea is\nestablished beyond question. The philosophic resignation of the guest\nto the fate awaiting him in the dubious decoction proclaims that in this\nsingle instance the Oriental spirit reigns supreme.",
    "The earliest record of tea in European writing is said to be found in\nthe statement of an Arabian traveller, that after the year 879 the main\nsources of revenue in Canton were the duties on salt and tea. Marco Polo\nrecords the deposition of a Chinese minister of finance in 1285 for his\narbitrary augmentation of the tea-taxes. It was at the period of the\ngreat discoveries that the European people began to know more about\nthe extreme Orient. At the end of the sixteenth century the Hollanders\nbrought the news that a pleasant drink was made in the East from the\nleaves of a bush. The travellers Giovanni Batista Ramusio (1559), L.\nAlmeida (1576), Maffeno (1588), Tareira (1610), also mentioned tea. In\nthe last-named year ships of the Dutch East India Company brought the\nfirst tea into Europe. It was known in France in 1636, and reached\nRussia in 1638. England welcomed it in 1650 and spoke of it as \"That\nexcellent and by all physicians approved China drink, called by the\nChineans Tcha, and by other nations Tay, alias Tee.\"",
    "Like all good things of the world, the propaganda of Tea met with\nopposition. Heretics like Henry Saville (1678) denounced drinking it as\na filthy custom. Jonas Hanway (Essay on Tea, 1756) said that men seemed\nto lose their stature and comeliness, women their beauty through the\nuse of tea. Its cost at the start (about fifteen or sixteen shillings\na pound) forbade popular consumption, and made it \"regalia for high\ntreatments and entertainments, presents being made thereof to princes\nand grandees.\" Yet in spite of such drawbacks tea-drinking spread with\nmarvelous rapidity. The coffee-houses of London in the early half of the\neighteenth century became, in fact, tea-houses, the resort of wits like\nAddison and Steele, who beguiled themselves over their \"dish of tea.\"\nThe beverage soon became a necessity of life--a taxable matter. We are\nreminded in this connection what an important part it plays in modern\nhistory. Colonial America resigned herself to oppression until human\nendurance gave way before the heavy duties laid on Tea. American\nindependence dates from the throwing of tea-chests into Boston harbour.",
    "There is a subtle charm in the taste of tea which makes it irresistible\nand capable of idealisation. Western humourists were not slow to mingle\nthe fragrance of their thought with its aroma. It has not the arrogance\nof wine, the self-consciousness of coffee, nor the simpering innocence\nof cocoa. Already in 1711, says the Spectator: \"I would therefore in a\nparticular manner recommend these my speculations to all well-regulated\nfamilies that set apart an hour every morning for tea, bread and butter;\nand would earnestly advise them for their good to order this paper to\nbe punctually served up and to be looked upon as a part of the\ntea-equipage.\" Samuel Johnson draws his own portrait as \"a hardened and\nshameless tea drinker, who for twenty years diluted his meals with only\nthe infusion of the fascinating plant; who with tea amused the evening,\nwith tea solaced the midnight, and with tea welcomed the morning.\"",
    "Charles Lamb, a professed devotee, sounded the true note of Teaism when\nhe wrote that the greatest pleasure he knew was to do a good action by\nstealth, and to have it found out by accident. For Teaism is the art of\nconcealing beauty that you may discover it, of suggesting what you dare\nnot reveal. It is the noble secret of laughing at yourself, calmly yet\nthoroughly, and is thus humour itself,--the smile of philosophy. All\ngenuine humourists may in this sense be called tea-philosophers,\nThackeray, for instance, and of course, Shakespeare. The poets of the\nDecadence (when was not the world in decadence?), in their protests\nagainst materialism, have, to a certain extent, also opened the way to\nTeaism. Perhaps nowadays it is our demure contemplation of the Imperfect\nthat the West and the East can meet in mutual consolation.",
    "The Taoists relate that at the great beginning of the No-Beginning,\nSpirit and Matter met in mortal combat. At last the Yellow Emperor, the\nSun of Heaven, triumphed over Shuhyung, the demon of darkness and earth.\nThe Titan, in his death agony, struck his head against the solar vault\nand shivered the blue dome of jade into fragments. The stars lost their\nnests, the moon wandered aimlessly among the wild chasms of the night.\nIn despair the Yellow Emperor sought far and wide for the repairer of\nthe Heavens. He had not to search in vain. Out of the Eastern sea rose a\nqueen, the divine Niuka, horn-crowned and dragon-tailed, resplendent\nin her armor of fire. She welded the five-coloured rainbow in her magic\ncauldron and rebuilt the Chinese sky. But it is told that Niuka forgot\nto fill two tiny crevices in the blue firmament. Thus began the dualism\nof love--two souls rolling through space and never at rest until they\njoin together to complete the universe. Everyone has to build anew his\nsky of hope and peace.",
    "The heaven of modern humanity is indeed shattered in the Cyclopean\nstruggle for wealth and power. The world is groping in the shadow of\negotism and vulgarity. Knowledge is bought through a bad conscience,\nbenevolence practiced for the sake of utility. The East and the West,\nlike two dragons tossed in a sea of ferment, in vain strive to\nregain the jewel of life. We need a Niuka again to repair the grand\ndevastation; we await the great Avatar. Meanwhile, let us have a sip of\ntea. The afternoon glow is brightening the bamboos, the fountains are\nbubbling with delight, the soughing of the pines is heard in our kettle.\nLet us dream of evanescence, and linger in the beautiful foolishness of\nthings."
  ],
  "guideIntro": [
    "Okakura wrote in English in 1906 to explain tea culture across an unequal East–West encounter. Tea becomes a small practice through which he discusses taste, imperial caricature, imperfection, and the possibility of mutual recognition."
  ],
  "notes": {
    "6": "The “greatness of little things” reverses scale: refinement is the ability to perceive value without demanding monumentality. The line also rebukes Western spectators who reduce ceremony to exotic fuss.",
    "12": "Tea is called the one Asian ceremony the West accepts. The hospitality of the cup is real, but Okakura keeps the asymmetry visible: a commodity travels more easily than the people and ideas attached to it.",
    "18": "The shattered modern heaven enlarges Teaism into social criticism. The cup is not an escape from industrial competition; it is a deliberately fragile counter-practice."
  },
  "audio": {}
};
