// Knows content — people (personal domain).
// Every factual claim here was checked against the repo's verified dossiers or
// well-established public record. Where a famous story is legend, the text says
// so instead of repeating it as fact.
window.KNOWS_PARTS = window.KNOWS_PARTS || [];
window.KNOWS_PARTS.push([

{
  id: "shelf-anchors",
  domain: "personal",
  title: "The Shelf — your anchors",
  blurb: "The twelve confirmed anchors. Pre-marked from reading history; they mostly exist here as lineage hubs.",
  items: [
    { id: "david-choe", kind: "person", name: "David Choe",
      hook: "Muralist and gambler who painted Facebook's first office and took stock instead of cash; DVDASA; Dirty Hands.",
      why: "Deepest anchor on the shelf — the study is feeling converted straight into action, and then learning, late, to feel instead of enact.",
      learn: [{ label: "Dirty Hands trailer (the 2000–08 documentary)", url: "https://www.youtube.com/watch?v=seo3k_UDX1o" },
              { label: "His blog, unbroken 1999–2024", url: "https://www.davidchoe.com/blog" }],
      preVerdict: "know", evidence: "own creator map + corpus in the repo" },
    { id: "andre-agassi", kind: "person", name: "Andre Agassi",
      hook: "Eight majors; handed an image instead of a self; confessed it in Open and rebuilt from No. 141 by choosing the thing he claimed to hate.",
      why: "Already read — Open stays retired from recommendations. He remains the hub for the tennis-lineage cards below.",
      up: ["brad-gilbert", "gil-reyes", "jr-moehringer", "nick-bollettieri"],
      learn: [{ label: "Served with Andy Roddick — the definitive late interview (1:44:55)", url: "https://www.youtube.com/watch?v=zogXUxUvR1s" }],
      preVerdict: "know", evidence: "read Open (2026)" },
    { id: "anthony-bourdain", kind: "person", name: "Anthony Bourdain",
      hook: "Bought trust with a confession (Kitchen Confidential), then used the trust to listen to the whole world eat.",
      why: "Voice anchor. His daily jiu-jitsu from age 58 — gold at an IBJJF open at 59 — is the shelf's cleanest proof of an exercise-first operating system.",
      up: ["george-orwell", "hunter-s-thompson", "renzo-gracie"],
      learn: [{ label: "Bourdain Confidential (Popula, 2018)", url: "https://popula.com/2018/07/15/bourdain-confidential/" }],
      preVerdict: "know", evidence: "Kitchen Confidential = chosen driving audio" },
    { id: "george-orwell", kind: "person", name: "George Orwell",
      hook: "Put his body where his beliefs were (shot through the throat in Spain), then reported against his own side in windowpane prose.",
      why: "The anti-cant standard the whole shelf is measured against.",
      up: ["jonathan-swift"],
      learn: [{ label: "A Life in Pictures (BBC 2003 — every spoken word is Orwell's own prose)", url: "https://archive.org/details/youtube-s6txpumkY5I" },
              { label: "Orwell Foundation free essay archive", url: "https://www.orwellfoundation.com/" }],
      preVerdict: "know", evidence: "four essays shelved and read" },
    { id: "takehiko-inoue", kind: "person", name: "Takehiko Inoue",
      hook: "Ended Slam Dunk at its peak, re-apprenticed himself from pen to brush for Vagabond, and named his hiatus 'a death for myself as an artist.'",
      why: "The mastery-and-struggle signal — killing your own successes to stay honest.",
      up: ["eiji-yoshikawa", "osamu-tezuka"],
      learn: [{ label: "NHK Professional (2009, a year embedded — fan-subbed, fragile link)", url: "https://www.youtube.com/watch?v=sj_mXSJ3v30" },
              { label: "The hiatus interviews ('a death for myself as an artist')", url: "https://mangabrog.wordpress.com/" }],
      preVerdict: "know", evidence: "Vagabond + Real read; 'strongest mastery signal'" },
    { id: "kentaro-miura", kind: "person", name: "Kentaro Miura",
      hook: "One man, one work, one desk, thirty-two years — Berserk's engine and trap were the same compounding skill; died at 54 mid-story.",
      why: "The unbounded-retreat cautionary tale on your own shelf.",
      up: ["osamu-tezuka"],
      learn: [{ label: "Great Berserk Exhibition interview (Dec 2020 — his only substantial on-camera appearance, subbed)", url: "https://www.youtube.com/watch?v=-SqR0zmXfJU" }],
      preVerdict: "know", evidence: "Berserk read; dossier built" },
    { id: "moebius", kind: "person", name: "Moebius / Jean Giraud",
      hook: "Ran two protected working modes — Gir the serial professional, Moebius the explorer — and late in life put them on the same page.",
      why: "The reference image for stage-by-stage artistic change.",
      learn: [{ label: "In Search of Moebius (BBC Four, 52:15)", url: "https://www.youtube.com/watch?v=jNas99oEXBU" },
              { label: "An Evening with Moebius (CTN 2010, 1:55:47)", url: "https://www.youtube.com/watch?v=Qbil5cQ0gbo" }],
      preVerdict: "know", evidence: "calibration benchmark documentary studied" },
    { id: "seneca", kind: "person", name: "Seneca",
      hook: "The first great writer whose subject was the gap between ideals and conduct — attacked for it, answered in print, closed it at death.",
      why: "Actively on the nightstand. De Tranquillitate opens with your exact Sunday complaint: the restless in-between state.",
      learn: [{ label: "On the Shortness of Life — reader on this site", url: "/wisdom/seneca-shortness-of-life/" },
              { label: "Tacitus, Annals 15.60–64 — the death, primary", url: "https://en.wikisource.org/wiki/The_Annals_(Tacitus)/Book_15" }],
      preVerdict: "know", evidence: "actively reading; creator map in repo" },
    { id: "terence-tao", kind: "person", name: "Terence Tao",
      hook: "A career spent converting private magic into public method; the only shelf anchor alive and posting.",
      why: "The working model for turning talent into procedure. His career-advice tree is the anti-genius doctrine from the far tail of genius.",
      up: ["paul-erdos"],
      learn: [{ label: "Career advice tree", url: "https://terrytao.wordpress.com/career-advice/" },
              { label: "'A Close Call' — nearly failing the Princeton generals (AMS, 2020)", url: "https://www.ams.org/notices/202007/rnoti-p1007.pdf" }],
      preVerdict: "know", evidence: "reading the genius essay (2026-07)" },
    { id: "haruki-murakami", kind: "person", name: "Haruki Murakami",
      hook: "Built a boring machine to reach a dangerous place — 4 a.m. writing, afternoon running, repetition as mesmerism.",
      why: "The routine-as-safety-protocol model behind the morning-anchor idea.",
      up: ["raymond-chandler", "franz-kafka"],
      learn: [{ label: "Paris Review, Art of Fiction 182", url: "https://www.theparisreview.org/interviews/2/the-art-of-fiction-no-182-haruki-murakami" }],
      preVerdict: "know", evidence: "Barn Burning loved; running memoir excerpt read" },
    { id: "hayao-miyazaki", kind: "person", name: "Hayao Miyazaki",
      hook: "Believes all dreams are cursed and draws anyway — 'filmmaking only brings suffering,' then back to the desk for thirty years.",
      why: "Porco Rosso — 'a fun movie for middle-aged businessmen whose brains became tofu from overwork' — was written for the exact tiredness this ledger tracks.",
      up: ["osamu-tezuka", "isao-takahata", "moebius"],
      learn: [{ label: "10 Years with Hayao Miyazaki (NHK, free — Ep. 3 is THE one)", url: "https://www3.nhk.or.jp/nhkworld/en/shows/10yearshayaomiyazaki/" },
              { label: "The 2004 Miyazaki–Moebius filmed talk (6:03)", url: "https://www.youtube.com/watch?v=2L0YgdIpXas" }],
      preVerdict: "know", evidence: "Porco Rosso 'might be my favorite'" },
    { id: "katsuhiro-otomo", kind: "person", name: "Katsuhiro Otomo",
      hook: "Akira — 'the story of my own teenage years, rewritten to take place in the future' — run by a control absolutist who drew 738 storyboard pages himself.",
      why: "The control-as-craft pole of the shelf; opened a new studio at 72.",
      up: ["osamu-tezuka", "moebius"],
      learn: [{ label: "Akira Production Report (1988, free)", url: "https://archive.org/details/Akira_Production_Report_1989" }],
      preVerdict: "know", evidence: "Akira + Memories deep analysis in repo" }
  ]
},

{
  id: "tennis-lineage",
  domain: "personal",
  title: "Tennis lineage",
  blurb: "The people behind the people — coaches, pioneers, and the thinking-player tradition Agassi came from.",
  items: [
    { id: "brad-gilbert", kind: "person", name: "Brad Gilbert",
      hook: "Reached world No. 4 on tactics over talent, wrote Winning Ugly, then coached Agassi through six of his eight majors (1994–2002).",
      why: ["The codifier of the mental game. Winning Ugly is the ur-text of playing percentages with limited weapons — scouting, score management, opponent psychology — which is exactly the layer a strong club player can actually import, unlike pro technique.",
            "In Open, Gilbert is the voice that rebuilds Agassi's brain after 1997. If Open landed, Gilbert is the next-door room."],
      learn: [{ label: "Winning Ugly (1993)", url: "https://en.wikipedia.org/wiki/Brad_Gilbert" }],
      quiz: [
        { q: "Winning Ugly is fundamentally a book about—", choices: ["Percentage play and mental warfare with limited weapons", "Modern serve technique", "Junior development pathways", "Fitness periodization"], a: 0,
          why: "Gilbert's whole claim: matches at every level are lost to bad decisions before bad strokes. He built a No. 4 ranking out of scouting and score management." },
        { q: "As Agassi's coach from 1994, Gilbert's on-record contribution was—", choices: ["Rebuilding him as a percentage player who broke opponents' patterns", "Overhauling his forehand grip", "Moving him to serve-and-volley", "Cutting his schedule to majors only"], a: 0,
          why: "Open describes it directly: Gilbert taught him to stop trying to hit a winner on every ball and start solving the man across the net." }
      ] },
    { id: "arthur-ashe", kind: "person", name: "Arthur Ashe",
      hook: "Won the first open-era US Open (1968) and took down prime Connors at Wimbledon '75 with off-pace tactics; the sport's conscience until AIDS took him in 1993.",
      why: ["Two reasons. The 1975 final is the greatest tactical upset in tennis — Ashe beat a peak Connors by giving him nothing to hit, the Winning Ugly thesis executed twenty years early.",
            "And McPhee's Levels of the Game — built point-by-point around one 1968 Ashe match — is arguably the best tennis book ever written: a whole person read through how he plays."],
      learn: [{ label: "Levels of the Game (John McPhee, 1969)", url: "https://en.wikipedia.org/wiki/Levels_of_the_Game" },
              { label: "Days of Grace (memoir)", url: "https://en.wikipedia.org/wiki/Arthur_Ashe" }],
      quiz: [
        { q: "How did Ashe beat prime Connors in the 1975 Wimbledon final?", choices: ["Took pace off — soft angles and junk until Connors self-destructed", "Out-hit him from the baseline", "Served-and-volleyed on every point", "Wore him down in five sets"], a: 0,
          why: "Ashe, a natural power player, deliberately fed Connors dead pace. It's the canonical proof that the right plan beats the better hitter." },
        { q: "Levels of the Game is structured around—", choices: ["A single 1968 Ashe–Graebner match, point by point", "Ashe's whole career year by year", "The 1975 Wimbledon final", "Interviews with rivals after retirement"], a: 0,
          why: "McPhee reads two entire lives — race, class, upbringing, style — out of one semifinal. A model for seeing a person in how they play." }
      ] },
    { id: "althea-gibson", kind: "person", name: "Althea Gibson",
      hook: "Broke tennis's color line — first Black player to win a major (French, 1956), then Wimbledon and the US Nationals back-to-back in 1957–58.",
      why: ["Before Ashe there was Gibson, and she had it harder: barred from most tournaments until 1950, learned on Harlem's police-league paddle courts, and after tennis had to start over again as the first Black woman in pro golf because tennis paid amateurs nothing.",
            "Her arc is also an honest one about what pioneering costs — fame without money, and decades of near-obscurity before the sport re-embraced her."],
      learn: [{ label: "I Always Wanted to Be Somebody (1958)", url: "https://en.wikipedia.org/wiki/Althea_Gibson" }],
      quiz: [
        { q: "What did Gibson do after leaving amateur tennis?", choices: ["Became the first Black woman on the LPGA golf tour", "Coached at a university", "Turned pro on the tennis tour", "Left sports entirely"], a: 0,
          why: "There was no professional women's tennis to join — so she broke a second sport's color line instead. That's the pre-open-era economics in one life." },
        { q: "Gibson's first major title came at—", choices: ["The 1956 French Championships", "Wimbledon 1951", "The 1950 US Nationals", "The 1960 Australian Championships"], a: 0,
          why: "Paris, 1956 — six years after she was first allowed to enter the US Nationals at all. Wimbledon and the US followed in 1957 and 1958, twice each." }
      ] },
    { id: "steffi-graf", kind: "person", name: "Steffi Graf",
      hook: "The only Golden Slam in history — all four majors plus Olympic gold in one season (1988) — 22 majors total; married Agassi in 2001.",
      why: ["The counter-model standing right inside Open: where Agassi performed and unraveled in public, Graf executed and stayed private. Same manufactured-prodigy childhood (her father was the template tennis parent), radically different response to it.",
            "Technically she's the footwork-economy model — a one-wing forehand game made unbeatable by movement."],
      learn: [{ label: "Graf career overview", url: "https://en.wikipedia.org/wiki/Steffi_Graf" }],
      quiz: [
        { q: "The 'Golden Slam' — still unique to Graf — means—", choices: ["All four majors plus Olympic gold in one calendar year", "All four majors at least four times each", "Winning a major without dropping a set", "Holding all four majors at once across two years"], a: 0,
          why: "1988: Melbourne, Paris, Wimbledon, New York, then Seoul gold. The Olympics had just returned tennis that year — right player, right season, never repeated." }
      ] },
    { id: "rod-laver", kind: "person", name: "Rod Laver",
      hook: "The only player of any gender with two calendar Grand Slams (1962 and 1969) — with five prime years missing in between because professionals were banned.",
      why: ["The hinge of tennis history: his 1962 Slam came as an amateur, his 1969 Slam in the Open era against everyone — and from 1963–67 he couldn't enter majors at all, having turned pro. Add those years back and the records conversation changes.",
            "A measurement lesson as much as a tennis one: the record books quietly encode who was allowed to compete."],
      learn: [{ label: "Laver and the Open era", url: "https://en.wikipedia.org/wiki/Rod_Laver" }],
      quiz: [
        { q: "Why is Laver's 1969 Grand Slam considered greater than his 1962 one?", choices: ["1969 was in the Open era, against the professionals; 1962 was amateurs only", "1969 had a stronger draw due to more countries entering", "He was older and injured in 1969", "1962 was only three majors"], a: 0,
          why: "Between the two, he was banned from the majors for five prime years for being professional. The 1969 Slam beat everybody there was." }
      ] },
    { id: "billie-jean-king", kind: "person", name: "Billie Jean King",
      hook: "39 major titles, the 1973 Battle of the Sexes, founder of the WTA, and the reason the US Open paid women equally from 1973.",
      why: ["The organizer archetype — an athlete who built institutions while still competing. The WTA, the players' union threat, equal prize money: all negotiated from active-player leverage.",
            "Relevant beyond tennis to anyone trying to build a community or league from nothing — she is the case study in converting play into infrastructure."],
      learn: [{ label: "King and the founding of the WTA", url: "https://en.wikipedia.org/wiki/Billie_Jean_King" }] },
    { id: "martina-navratilova", kind: "person", name: "Martina Navratilova",
      hook: "167 singles titles — still the record — 59 majors across disciplines, and the first player to treat training as sports science in the early 1980s.",
      why: ["The professionalization pioneer on the women's side: nutrition, weights, a full support team when nobody had one — the approach Lendl mirrored and everyone now copies.",
            "Also came out in 1981 at the peak of her earning years, when it cost real money. Courage with a price tag attached is the kind the shelf respects."],
      learn: [{ label: "Navratilova's training revolution", url: "https://en.wikipedia.org/wiki/Martina_Navratilova" }] },
    { id: "pancho-gonzales", kind: "person", name: "Pancho Gonzales",
      hook: "Self-taught on LA public courts; possibly the best player of the 1950s — and nearly invisible in the record because professionals were locked out of the majors.",
      why: ["An LA story and a measurement story at once: Mexican-American kid, banned from junior tennis for truancy, wins the US Nationals twice, turns pro at 21 — and disappears from the official record while dominating the pro tour for a decade.",
            "At 41 he won the longest Wimbledon match ever played to that point (112 games, 1969) over a man 16 years younger. Greatness the record books can't see."],
      learn: [{ label: "Gonzales and the pro tour years", url: "https://en.wikipedia.org/wiki/Pancho_Gonzales" }] },
    { id: "bill-tilden", kind: "person", name: "Bill Tilden",
      hook: "Owned the 1920s — and wrote the first serious tactics book, Match Play and the Spin of the Ball (1925), which still reads as modern.",
      why: ["The origin of the thinking-player tradition Gilbert descends from: spin as strategy, opponent psychology, percentage play — in 1925.",
            "Stated honestly: he was later twice convicted for sexual misconduct with minors and died broke and shunned. The tradition keeps the book's ideas without laundering the man."],
      learn: [{ label: "Match Play and the Spin of the Ball", url: "https://en.wikipedia.org/wiki/Bill_Tilden" }] },
    { id: "suzanne-lenglen", kind: "person", name: "Suzanne Lenglen",
      hook: "Lost once in seven years (1919–26), made women's tennis a headline act, and became the first global female sports celebrity; Roland Garros named a stadium for her.",
      why: "Performance plus spectacle before either was normal — she drew crowds that men's finals didn't, fifty years before equal-pay arguments, which is why she's the buried root of the King story above.",
      learn: [{ label: "Lenglen's run of the 1920s", url: "https://en.wikipedia.org/wiki/Suzanne_Lenglen" }] },
    { id: "ivan-lendl", kind: "person", name: "Ivan Lendl",
      hook: "Lost his first four major finals, then won eight — by being the first man to systematize everything: diet, weights, equipment, percentage baseline play.",
      why: ["The conversion arc: the game's most famous early-final loser turned into its most reliable closer by process, not talent. If conversion is the leak, Lendl is the patron saint of fixing it.",
            "His systemization is the direct template for the modern baseline era — Djokovic is Lendl's thesis perfected."],
      learn: [{ label: "Lendl's system", url: "https://en.wikipedia.org/wiki/Ivan_Lendl" }],
      quiz: [
        { q: "Lendl's career shape was—", choices: ["Lost his first four major finals, then won eight majors", "Won early, faded young", "Dominated juniors, never won a major", "Won only on clay"], a: 0,
          why: "The canonical proof that closing is a learnable skill: same player, same strokes, different process — from choker label to eight majors and 19 finals." }
      ] },
    { id: "nick-bollettieri", kind: "person", name: "Nick Bollettieri",
      hook: "Built the Florida academy that produced Agassi, Sharapova, and ten world No. 1s — the factory model of tennis development.",
      why: "Both sides of the academy question in one man: Open portrays the place as a prison camp, and it also worked. Any opinion about how tennis should be taught has to answer Bollettieri.",
      learn: [{ label: "The Bollettieri academy story", url: "https://en.wikipedia.org/wiki/Nick_Bollettieri" }] }
  ]
},

{
  id: "shelf-upstream",
  domain: "personal",
  title: "Upstream of the shelf",
  blurb: "Documented feeders of your anchors — the people your people learned from, translated, or trained under.",
  items: [
    { id: "jr-moehringer", kind: "person", name: "J.R. Moehringer",
      hook: "Pulitzer journalist who ghostwrote Open from 250 taped hours — and declined to put his name on the cover.",
      why: "The craft behind the voice you liked: Open's honesty is engineered, and Moehringer's own New Yorker essay on ghostwriting explains exactly how. His memoir The Tender Bar is the same voice on his own life.",
      learn: [{ label: "The ghostwriting essay (New Yorker, 2023)", url: "https://www.newyorker.com/magazine/2023/05/22/jr-moehringer-ghostwriter-prince-harry-memoir-spare" }] },
    { id: "gil-reyes", kind: "person", name: "Gil Reyes",
      hook: "Agassi's strength coach and chosen father figure — 'Papa Gil'; Agassi named his son Jaden Gil.",
      why: "The model of coaching-as-care in Open: custom-built equipment, obsessive measurement, total trust. The counterweight to the Bollettieri factory in the same book.",
      learn: [{ label: "Papa Gil (tennis.com)", url: "https://www.tennis.com/news/articles/papa-gil-gil-reyes-andre-agassi" }] },
    { id: "renzo-gracie", kind: "person", name: "Renzo Gracie",
      hook: "Third-generation member of the family that built Brazilian jiu-jitsu; made New York a BJJ capital; coached Bourdain daily from his late fifties.",
      why: "The teacher of late-starting adults. Bourdain's every-day training habit — the one that made him feel 'miserable and worthless' to skip — ran through Renzo's academy.",
      learn: [{ label: "Renzo Gracie Academy lineage", url: "https://en.wikipedia.org/wiki/Renzo_Gracie" }] },
    { id: "hunter-s-thompson", kind: "person", name: "Hunter S. Thompson",
      hook: "Invented gonzo journalism — the reporter inside the story, style as weapon; a model Bourdain claimed openly.",
      why: "Kitchen Confidential's swagger has a return address. Reading Thompson shows which parts of Bourdain's voice were inherited and which were his own — the honest way to study any voice you admire.",
      learn: [{ label: "Fear and Loathing in Las Vegas (1971)", url: "https://en.wikipedia.org/wiki/Hunter_S._Thompson" }],
      quiz: [
        { q: "'Gonzo' journalism means—", choices: ["The reporter is a participant in the story, subjectivity on display", "Anonymous sourcing", "Long-form investigative series", "Strictly neutral wire-service style"], a: 0,
          why: "Thompson abandoned the pretense of objectivity and made the reporting self part of the report — the move Bourdain imported into food television." }
      ] },
    { id: "raymond-chandler", kind: "person", name: "Raymond Chandler",
      hook: "Made crime fiction literature on style alone — Philip Marlowe, The Long Goodbye; Murakami translated him and names him a model.",
      why: "An LA writer at the root of a Tokyo voice you love: Murakami's flat, precise, simile-lit sentences are openly Chandler-schooled. Also the best prose ever written about your own city's streets.",
      learn: [{ label: "The Long Goodbye (1953)", url: "https://en.wikipedia.org/wiki/Raymond_Chandler" }],
      quiz: [
        { q: "Murakami's documented connection to Chandler is—", choices: ["He translated The Long Goodbye into Japanese and cites it as a model", "They corresponded for years", "He wrote a Marlowe novel", "Chandler reviewed his first book"], a: 0,
          why: "Murakami's 2007 translation, with his admiring afterword, is the paper trail — the voice lineage runs Los Angeles → Tokyo, verifiably." }
      ] },
    { id: "franz-kafka", kind: "person", name: "Franz Kafka",
      hook: "Insurance lawyer by day; The Metamorphosis and The Trial by night; mostly unpublished at his death — he asked for the manuscripts to be burned.",
      why: "Murakami named a novel for him, and the reader on this site already holds him — the shortest path from a shelf-anchor's influence to an actual read tonight.",
      learn: [{ label: "Kafka reader — on this site", url: "/wisdom/books/kafka-reader/" }],
      quiz: [
        { q: "Kafka's instruction to Max Brod about his manuscripts was—", choices: ["Burn them unread — Brod refused", "Publish them immediately", "Donate them to Prague's library", "Give them to his sisters"], a: 0,
          why: "Nearly everything we call 'Kafka' exists because his best friend disobeyed him. A permanent complication for anyone romanticizing the private notebook." }
      ] },
    { id: "eiji-yoshikawa", kind: "person", name: "Eiji Yoshikawa",
      hook: "His 1935 Musashi serialization invented the popular image of the swordsman; Vagabond adapts it — and Inoue drew the covers on today's paperbacks.",
      why: "The bridge between an anchor (Inoue) and a primary source (Musashi's own Five Rings): novel → manga → the cave-written original, each one level closer to the man.",
      learn: [{ label: "Musashi (the novel)", url: "https://en.wikipedia.org/wiki/Eiji_Yoshikawa" }] },
    { id: "osamu-tezuka", kind: "person", name: "Osamu Tezuka",
      hook: "The 'god of manga' — Astro Boy, Black Jack, Phoenix, roughly 150,000 pages — the industrial and artistic root Otomo, Miyazaki, Inoue, and Miura all grew inside or against.",
      why: "Four of your anchors trace to him — by inheritance or by rebellion (Miyazaki's criticisms of Tezuka's animation economics are famous and on record). Knowing Tezuka turns four separate tastes into one family tree.",
      learn: [{ label: "Tezuka's scale and influence", url: "https://en.wikipedia.org/wiki/Osamu_Tezuka" }],
      quiz: [
        { q: "Tezuka's nickname and rough page count are—", choices: ["'God of manga'; ~150,000 pages", "'Father of anime'; ~20,000 pages", "'The Machine'; ~500,000 pages", "'Sensei zero'; ~75,000 pages"], a: 0,
          why: "The volume is the point: an entire medium's grammar worked out by one person at industrial output. Everyone after either used his vocabulary or defined themselves against it." }
      ] },
    { id: "isao-takahata", kind: "person", name: "Isao Takahata",
      hook: "Ghibli's other founder — Grave of the Fireflies, Only Yesterday, Kaguya — Miyazaki's senior, rival, and conscience for fifty years.",
      why: "You can't finish understanding Miyazaki without the man he measured himself against; the NHK documentary's most raw moments are about Takahata.",
      learn: [{ label: "Takahata at Ghibli", url: "https://en.wikipedia.org/wiki/Isao_Takahata" }] },
    { id: "jonathan-swift", kind: "person", name: "Jonathan Swift",
      hook: "Gulliver's Travels as weaponized satire; Orwell wrestled with him head-on in 'Politics vs. Literature' (1946).",
      why: "Orwell's essay on Swift is Orwell explaining his own trade — how a writer he half-despised still achieved permanence. Reading the pair is a masterclass in disagreeing with an influence.",
      learn: [{ label: "Politics vs. Literature (Orwell Foundation)", url: "https://www.orwellfoundation.com/the-orwell-foundation/orwell/essays-and-other-works/politics-vs-literature-an-examination-of-gullivers-travels/" }],
      quiz: [
        { q: "Orwell's verdict on Swift in 'Politics vs. Literature' is roughly—", choices: ["Politically dubious, artistically permanent — and worth studying for exactly that tension", "A flawless model to imitate", "Overrated in every respect", "Great politics, weak prose"], a: 0,
          why: "Orwell calls Gulliver's Travels a book he'd keep if only six survived — while spending pages attacking its worldview. That's the shelf's honesty standard, applied by its own standard-setter." }
      ] }
  ]
},

{
  id: "math-science",
  domain: "personal",
  title: "Math & science greats",
  blurb: "The deeper bench — people school mentioned once or skipped, each with a reason they still matter to your lanes.",
  items: [
    { id: "leonhard-euler", kind: "person", name: "Leonhard Euler",
      hook: "The most prolific mathematician in history — e, π, f(x) notation, graph theory from the Königsberg bridges — with half the work produced after he went blind.",
      why: "Every network diagram and pathfinding algorithm in your projects descends from one 1736 walk-across-bridges puzzle. Also the shelf's cleanest case of output as a practiced system rather than a mood.",
      learn: [{ label: "Euler overview", url: "https://en.wikipedia.org/wiki/Leonhard_Euler" }],
      quiz: [
        { q: "The Königsberg bridges problem mattered because—", choices: ["Solving it founded graph theory — reasoning about connections while ignoring geometry", "It produced the first calculus proof", "It measured the earth's circumference", "It was the first computer program"], a: 0,
          why: "Euler saw that only the pattern of connections mattered, not the map. Every graph, network, and route algorithm since is that one abstraction." },
        { q: "After losing his sight, Euler—", choices: ["Kept producing at full rate by dictation for ~15 more years", "Retired from mathematics", "Only taught", "Switched to philosophy"], a: 0,
          why: "Roughly half his collected works date from the blind years. The machine was in his head; the eyes turned out to be optional." }
      ] },
    { id: "carl-friedrich-gauss", kind: "person", name: "Carl Friedrich Gauss",
      hook: "The 'prince of mathematics' — number theory, least squares, the normal distribution — the schoolboy 1-to-100 story is probably legend, the work is not.",
      why: "Least squares and the Gaussian are underneath every model, filter, and forecast you touch — chess evals, CV confidence, attribution. Honest note: the beloved 5050 anecdote can't be traced to a reliable source, so hold the work and drop the myth.",
      learn: [{ label: "Gauss overview", url: "https://en.wikipedia.org/wiki/Carl_Friedrich_Gauss" }] },
    { id: "evariste-galois", kind: "person", name: "Évariste Galois",
      hook: "Founded group theory and died in a duel at twenty (1832) — the final-night letter to a friend is real; 'invented it all that night' is romance.",
      why: "Group theory became the language of symmetry — which, via Noether, became the language of physics. Also the sharpest warning label on the romantic-genius myth: the legend actively obscures that he'd been writing it down for years.",
      learn: [{ label: "Galois — the record vs the legend", url: "https://en.wikipedia.org/wiki/%C3%89variste_Galois" }] },
    { id: "emmy-noether", kind: "person", name: "Emmy Noether",
      hook: "Noether's theorem — every symmetry implies a conservation law — arguably the deepest single idea in physics, proved while she was barred from a paid professorship.",
      why: "Einstein called her a genius in her New York Times obituary; her theorem is why energy conservation isn't an assumption but a consequence. The best answer to 'what did school skip?' in one person.",
      learn: [{ label: "Noether's theorem, plainly", url: "https://en.wikipedia.org/wiki/Emmy_Noether" }],
      quiz: [
        { q: "Noether's theorem links—", choices: ["Symmetries to conservation laws", "Primes to encryption", "Geometry to logic", "Chaos to computability"], a: 0,
          why: "Time symmetry gives energy conservation; space symmetry gives momentum. Physics' bookkeeping rules turn out to be consequences of symmetry — one theorem, 1918." }
      ] },
    { id: "srinivasa-ramanujan", kind: "person", name: "Srinivasa Ramanujan",
      hook: "Self-taught in Madras from one outdated textbook; mailed Hardy pages of results so strange Hardy judged they had to be true, since no one could invent them; dead at 32.",
      why: "The outer boundary of what untrained intuition can do — and proof that it still needed Hardy's system to land. Talent plus protocol, the shelf's recurring pair, at maximum contrast.",
      learn: [{ label: "The Man Who Knew Infinity (Kanigel)", url: "https://en.wikipedia.org/wiki/Srinivasa_Ramanujan" }],
      quiz: [
        { q: "Hardy's famous reasoning about Ramanujan's unsolicited letter was—", choices: ["The results must be true — no one would have the imagination to fake them", "The proofs were flawless", "He recognized the theorems from journals", "A colleague vouched for him"], a: 0,
          why: "Many results arrived without proof, some wrong — but the true ones were beyond invention. Hardy called finding him his greatest contribution to mathematics." }
      ] },
    { id: "gh-hardy", kind: "person", name: "G.H. Hardy",
      hook: "Ramanujan's discoverer and partner; A Mathematician's Apology (1940) is the classic defense of doing mathematics for beauty alone.",
      why: "The Apology is short enough for one sitting and is the purest statement of craft-for-its-own-sake on record — plus the frankest writing about being past one's peak, which is its secret subject.",
      learn: [{ label: "A Mathematician's Apology", url: "https://en.wikipedia.org/wiki/A_Mathematician%27s_Apology" }] },
    { id: "paul-erdos", kind: "person", name: "Paul Erdős",
      hook: "No home, one suitcase, 500+ collaborators — lived out of other mathematicians' guest rooms for decades; met ten-year-old Terence Tao in 1985, and the photo survives.",
      why: "The maximal collaboration model — mathematics as a distributed social organism — and the direct upstream link to your one living anchor. The Erdős number game is the original social graph.",
      learn: [{ label: "The Man Who Loved Only Numbers (Hoffman)", url: "https://en.wikipedia.org/wiki/Paul_Erd%C5%91s" }],
      quiz: [
        { q: "Erdős's working life was organized around—", choices: ["Traveling between collaborators' homes and co-writing everywhere", "A single university chair", "Solitary work in Budapest", "Industry consulting"], a: 0,
          why: "Around 1,500 papers with 500+ co-authors — he optimized his entire existence for collaboration throughput. The inverse of the lone-genius model, at equal magnitude." }
      ] },
    { id: "david-hilbert", kind: "person", name: "David Hilbert",
      hook: "Set the 20th century's agenda with 23 problems (1900) and a program to put all mathematics on provably solid ground — the program Gödel then demolished.",
      why: "The great agenda-setter: his problem list steered a century of work, and his Göttingen protected Noether when other faculties wouldn't. Knowing Hilbert makes Gödel legible.",
      learn: [{ label: "Hilbert's problems", url: "https://en.wikipedia.org/wiki/David_Hilbert" }] },
    { id: "kurt-godel", kind: "person", name: "Kurt Gödel",
      hook: "Proved in 1931 that any consistent system rich enough for arithmetic contains true statements it cannot prove — incompleteness, at 25.",
      why: "The permanent boundary stone on formal systems — relevant every time someone promises a complete, self-verifying anything. Later: Einstein said he went to the office mainly for the walks home with Gödel.",
      up: ["david-hilbert"],
      learn: [{ label: "Gödel's Proof (Nagel & Newman) — the classic 100-page explainer", url: "https://en.wikipedia.org/wiki/G%C3%B6del%27s_Proof" }],
      quiz: [
        { q: "Incompleteness says, roughly—", choices: ["A consistent system strong enough for arithmetic has truths it can't prove", "All mathematics is contradictory", "Nothing can be proved", "Computers can't do arithmetic"], a: 0,
          why: "It killed Hilbert's dream of a complete self-certifying mathematics — not by finding an error, but by proving the goal impossible from inside." }
      ] },
    { id: "alan-turing", kind: "person", name: "Alan Turing",
      hook: "Defined computation itself in 1936, led the break of naval Enigma, proposed the imitation game — prosecuted for homosexuality, dead at 41; the state apology came in 2009.",
      why: "Everything you run — agents, models, the machine itself — sits on the 1936 paper's abstraction. The life is also the century's starkest case of a society destroying the person it depended on.",
      learn: [{ label: "Turing — the 1936 paper and after", url: "https://en.wikipedia.org/wiki/Alan_Turing" }],
      quiz: [
        { q: "Turing's 1936 result established—", choices: ["A universal machine: one device can compute anything computable", "The first physical computer", "Binary arithmetic", "Encryption theory"], a: 0,
          why: "The universal machine is why software exists — hardware once, programs forever. Every model you call is a guest of that idea." }
      ] },
    { id: "claude-shannon", kind: "person", name: "Claude Shannon",
      hook: "Invented information theory in one 1948 paper — bit, entropy, channel capacity — then spent decades building juggling machines and chess programs for fun; met Turing over Bell Labs teatimes in 1943.",
      why: "Tokens, compression, bandwidth, entropy in your evals — all one man's paper. His portfolio-of-play working style (unicycles, gadgets, toy problems) is also the sanctioned-fun counterexample to grind culture.",
      up: ["alan-turing"],
      learn: [{ label: "The 1948 paper itself — readable, and free (PDF)", url: "https://people.math.harvard.edu/~ctm/home/text/others/shannon/entropy/entropy.pdf" },
              { label: "A Mind at Play (Soni & Goodman) — the biography", url: "https://en.wikipedia.org/wiki/Claude_Shannon" }],
      quiz: [
        { q: "Shannon's 1948 paper gave us—", choices: ["The bit, entropy, and channel capacity — information as measurable quantity", "The transistor", "The internet protocol", "Boolean algebra"], a: 0,
          why: "Before it, 'information' was a vague word; after it, a unit. Compression and every noisy-channel trick — including how model context gets budgeted — descend from it." },
        { q: "His earlier master's thesis (1937) showed—", choices: ["Boolean algebra could design switching circuits — the bridge from logic to hardware", "Radar could detect planes", "Telephones could carry video", "Chess was solvable"], a: 0,
          why: "Often called the most consequential master's thesis ever: logic became circuitry, and digital everything followed." }
      ] },
    { id: "john-von-neumann", kind: "person", name: "John von Neumann",
      hook: "Game theory, the stored-program computer architecture, Manhattan Project mathematics — and the fastest mind of his century by nearly every first-hand account.",
      why: "The architecture bearing his name is the reason 'load the weights, run the program' is a sentence. Also the standing rebuttal whenever someone says breadth is dead: he refounded four fields as a side effect.",
      learn: [{ label: "Von Neumann overview", url: "https://en.wikipedia.org/wiki/John_von_Neumann" }],
      quiz: [
        { q: "'Von Neumann architecture' means—", choices: ["Programs and data share one memory — the stored-program computer", "Parallel-only processing", "Quantum computation", "Analog circuits"], a: 0,
          why: "Code as data is why software can write, load, and modify software — the precondition for compilers, operating systems, and everything agentic." }
      ] },
    { id: "andrey-kolmogorov", kind: "person", name: "Andrey Kolmogorov",
      hook: "Put probability on axioms in 1933 — before him it was intuition with notation — and later founded the complexity measure bearing his name.",
      why: "Every confidence score, tracker filter, and forecast in your CV lane rests on the 1933 foundations. Kolmogorov complexity — 'the length of the shortest program that produces it' — is also the cleanest definition of simplicity you'll ever use.",
      learn: [{ label: "Kolmogorov overview", url: "https://en.wikipedia.org/wiki/Andrey_Kolmogorov" }] },
    { id: "alexander-grothendieck", kind: "person", name: "Alexander Grothendieck",
      hook: "Rebuilt algebraic geometry from beneath (schemes) with a thousand-page collaborative program — then renounced mathematics and spent his last decades as a Pyrenees hermit refusing all contact.",
      why: "Both poles in one life: the most generous system-builder of his era, and then the cautionary unbounded retreat — the Miura pattern at mathematical scale. The bounded/unbounded distinction from this week's journal, illustrated exactly.",
      learn: [{ label: "Grothendieck's rise and withdrawal", url: "https://en.wikipedia.org/wiki/Alexander_Grothendieck" }] }
  ]
}

]);
