window.ESSAY_TEXT = {
  "id": "chesterton-on-lying-in-bed",
  "title": "On Lying in Bed",
  "titleOriginal": null,
  "author": "G. K. Chesterton",
  "authorNative": null,
  "year": 1909,
  "language": "en",
  "kind": "essay",
  "why": "A tiny, delightful essay that flips the guilt script: lying in bed is innocent; what corrupts is turning minor habits into moral tests. Good antidote to optimization-guilt.",
  "themes": [
    "habit",
    "moralism",
    "play"
  ],
  "rightsNote": "Published 1909; public domain everywhere.",
  "sourceLabel": "Project Gutenberg eBook 8092 (Tremendous Trifles)",
  "sourcePage": "https://www.gutenberg.org/ebooks/8092",
  "provenance": "fetched (scripts/build_essays_sources.py; local mirror: 8092-0.txt)",
  "generated": "2026-07-11",
  "paragraphs": [
    "On Lying in Bed",
    "Lying in bed would be an altogether perfect and supreme experience if\nonly one had a coloured pencil long enough to draw on the ceiling.\nThis, however, is not generally a part of the domestic apparatus on the\npremises. I think myself that the thing might be managed with several\npails of Aspinall and a broom. Only if one worked in a really sweeping\nand masterly way, and laid on the colour in great washes, it might drip\ndown again on one's face in floods of rich and mingled colour like some\nstrange fairy rain; and that would have its disadvantages. I am afraid\nit would be necessary to stick to black and white in this form of\nartistic composition. To that purpose, indeed, the white ceiling would\nbe of the greatest possible use; in fact, it is the only use I think of\na white ceiling being put to.",
    "But for the beautiful experiment of lying in bed I might never have\ndiscovered it. For years I have been looking for some blank spaces in\na modern house to draw on. Paper is much too small for any really\nallegorical design; as Cyrano de Bergerac says, “Il me faut des géants.”\nBut when I tried to find these fine clear spaces in the modern rooms\nsuch as we all live in I was continually disappointed. I found an\nendless pattern and complication of small objects hung like a curtain of\nfine links between me and my desire. I examined the walls; I found them\nto my surprise to be already covered with wallpaper, and I found the\nwallpaper to be already covered with uninteresting images, all bearing\na ridiculous resemblance to each other. I could not understand why one\narbitrary symbol (a symbol apparently entirely devoid of any religious\nor philosophical significance) should thus be sprinkled all over my\nnice walls like a sort of small-pox. The Bible must be referring to\nwallpapers, I think, when it says, “Use not vain repetitions, as the\nGentiles do.” I found the Turkey carpet a mass of unmeaning colours,\nrather like the Turkish Empire, or like the sweetmeat called Turkish\nDelight. I do not exactly know what Turkish Delight really is; but I\nsuppose it is Macedonian Massacres. Everywhere that I went forlornly,\nwith my pencil or my paint brush, I found that others had unaccountably\nbeen before me, spoiling the walls, the curtains, and the furniture with\ntheir childish and barbaric designs.",
    ".....",
    "Nowhere did I find a really clear space for sketching until this\noccasion when I prolonged beyond the proper limit the process of lying\non my back in bed. Then the light of that white heaven broke upon my\nvision, that breadth of mere white which is indeed almost the definition\nof Paradise, since it means purity and also means freedom. But alas!\nlike all heavens, now that it is seen it is found to be unattainable;\nit looks more austere and more distant than the blue sky outside the\nwindow. For my proposal to paint on it with the bristly end of a broom\nhas been discouraged--never mind by whom; by a person debarred from all\npolitical rights--and even my minor proposal to put the other end of\nthe broom into the kitchen fire and turn it to charcoal has not been\nconceded. Yet I am certain that it was from persons in my position that\nall the original inspiration came for covering the ceilings of palaces\nand cathedrals with a riot of fallen angels or victorious gods. I am\nsure that it was only because Michael Angelo was engaged in the ancient\nand honourable occupation of lying in bed that he ever realized how the\nroof of the Sistine Chapel might be made into an awful imitation of a\ndivine drama that could only be acted in the heavens.",
    "The tone now commonly taken toward the practice of lying in bed is\nhypocritical and unhealthy. Of all the marks of modernity that seem to\nmean a kind of decadence, there is none more menacing and dangerous than\nthe exultation of very small and secondary matters of conduct at the\nexpense of very great and primary ones, at the expense of eternal ties\nand tragic human morality. If there is one thing worse than the modern\nweakening of major morals, it is the modern strengthening of minor\nmorals. Thus it is considered more withering to accuse a man of bad\ntaste than of bad ethics. Cleanliness is not next to godliness nowadays,\nfor cleanliness is made essential and godliness is regarded as an\noffence. A playwright can attack the institution of marriage so long as\nhe does not misrepresent the manners of society, and I have met Ibsenite\npessimists who thought it wrong to take beer but right to take prussic\nacid. Especially this is so in matters of hygiene; notably such matters\nas lying in bed. Instead of being regarded, as it ought to be, as\na matter of personal convenience and adjustment, it has come to be\nregarded by many as if it were a part of essential morals to get up\nearly in the morning. It is upon the whole part of practical wisdom; but\nthere is nothing good about it or bad about its opposite.",
    ".....",
    "Misers get up early in the morning; and burglars, I am informed, get\nup the night before. It is the great peril of our society that all its\nmechanisms may grow more fixed while its spirit grows more fickle.\nA man's minor actions and arrangements ought to be free, flexible,\ncreative; the things that should be unchangeable are his principles, his\nideals. But with us the reverse is true; our views change constantly;\nbut our lunch does not change. Now, I should like men to have strong and\nrooted conceptions, but as for their lunch, let them have it sometimes\nin the garden, sometimes in bed, sometimes on the roof, sometimes in the\ntop of a tree. Let them argue from the same first principles, but let\nthem do it in a bed, or a boat, or a balloon. This alarming growth of\ngood habits really means a too great emphasis on those virtues which\nmere custom can ensure, it means too little emphasis on those virtues\nwhich custom can never quite ensure, sudden and splendid virtues of\ninspired pity or of inspired candour. If ever that abrupt appeal is made\nto us we may fail. A man can get use to getting up at five o'clock in\nthe morning. A man cannot very well get used to being burnt for his\nopinions; the first experiment is commonly fatal. Let us pay a little\nmore attention to these possibilities of the heroic and unexpected.\nI dare say that when I get out of this bed I shall do some deed of an\nalmost terrible virtue.",
    "For those who study the great art of lying in bed there is one emphatic\ncaution to be added. Even for those who can do their work in bed (like\njournalists), still more for those whose work cannot be done in bed (as,\nfor example, the professional harpooners of whales), it is obvious that\nthe indulgence must be very occasional. But that is not the caution\nI mean. The caution is this: if you do lie in bed, be sure you do it\nwithout any reason or justification at all. I do not speak, of course,\nof the seriously sick. But if a healthy man lies in bed, let him do it\nwithout a rag of excuse; then he will get up a healthy man. If he\ndoes it for some secondary hygienic reason, if he has some scientific\nexplanation, he may get up a hypochondriac."
  ],
  "guideIntro": [
    "Chesterton uses a comic defense of staying in bed to attack standardized virtue. The target is less work than the modern habit of turning one schedule, posture, or use of time into a moral law for everyone."
  ],
  "notes": {
    "3": "The ceiling becomes a better drawing surface because the absurd premise frees perception. His method is to take a dismissed activity seriously until the respectable alternative starts to look arbitrary.",
    "6": "This is the turn from whimsy to polemic: compulsory early rising is called decadent because it replaces individual judgment with a public performance of health and industry."
  },
  "audio": {}
};
