/* Generated by scripts/build_kafka_reference_map.mjs from references.json. */
window.KAFKA_REFERENCE_MAP = {
  "schemaVersion": 1,
  "builtAtCutoff": "2026-07-20",
  "title": "The books inside Kafka on the Shore",
  "subtitle": "A chapter-located companion to Philip Gabriel's English translation, with direct titles separated from author-only, unresolved, and inferred references.",
  "sourceEdition": {
    "work": "Kafka on the Shore",
    "author": "Haruki Murakami",
    "translator": "Philip Gabriel",
    "publisher": "Knopf / Vintage",
    "publication": "2005 hardcover; 2006 paperback",
    "chapterCount": 49,
    "canonicalUrl": "https://www.penguinrandomhouse.com/books/118718/kafka-on-the-shore-by-haruki-murakami/9781400044818/",
    "rights": "Copyrighted novel. Wisdom stores edition metadata, chapter locators, original analysis, and source links only; no novel body or substitute transcript."
  },
  "evidenceUniverse": {
    "scope": "All 49 numbered chapters plus the Boy Named Crow framing sections in Philip Gabriel's English translation; book, play, poem, story, author-only, and in-novel library-title references are in scope. Music and film references are out of scope for this map.",
    "chapterAuditUrl": "https://kots140.blogspot.com/2011/07/kafka-on-shore-texts-referenced.html",
    "method": "A community chapter inventory was checked against chapter summaries, scholarly intertext work, publisher metadata, and lawful source editions. Ambiguous upgrades remain visibly unresolved or inferred."
  },
  "burtonTrail": {
    "novelLocator": "Chapter 5; Vintage paperback pages vary by printing (the commonly cited 2006 printing places the selection near page 36).",
    "selection": "Kafka chooses a multivolume Burton translation of The Arabian Nights. The later tale label in Gabriel's translation corresponds most closely to Burton's ‘The Sleeper and the Waker’ in Supplemental Nights, Volume 1.",
    "exactTaleLabel": "The Sleeper and the Waker",
    "exactTaleUrl": "https://www.gutenberg.org/cache/epub/3445/pg3445-images.html#link2H_4_0003",
    "exactVolumeUrl": "https://www.gutenberg.org/ebooks/3445",
    "coreStartUrl": "/wisdom/arabian-nights/reader/",
    "coreStartLabel": "Continue Burton's core Volume 1 in Wisdom",
    "correction": "Wisdom's existing reader is Burton's core Volume 1 (Project Gutenberg 3435), a valid start in the same translation project but not the supplemental volume containing the tale Kafka is shown reading. Burton's ten core volumes are Gutenberg 3435–3444; six supplemental volumes are 3445–3450."
  },
  "startIds": [
    "burton-nights-set",
    "soseki-miner",
    "akinari-chrysanthemum"
  ],
  "counterargument": "An allusion is not automatically a recommendation or a key that ‘solves’ the novel. Murakami also uses books as characterization, jokes, counterexamples, and structural echoes. Read one source only when it sharpens a live question in the novel.",
  "outputPrompt": "After one source, write one sentence: what did Murakami borrow—an image, a problem, or a structure—and what changed when he moved it into this novel?",
  "references": [
    {
      "id": "burton-nights-set",
      "title": "The Book of the Thousand Nights and a Night",
      "creator": "Traditional corpus; translated by Richard F. Burton",
      "chapter": "5",
      "kind": "book-series",
      "referenceStatus": "direct-title",
      "confidence": "high",
      "role": "Kafka's chosen library reading; the old stories become a freer and more vivid reality than the anonymous station crowd.",
      "sourceVersion": "Burton's ten-volume core translation (1885), followed by six Supplemental Nights volumes (1886–1888)",
      "sourceUrl": "https://www.gutenberg.org/ebooks/3435",
      "evidenceUrl": "https://journalofthenights.blogspot.com/2009/09/",
      "rights": "Public domain in the United States; Project Gutenberg source.",
      "accessMode": "internal-and-public-source",
      "canonicalSurface": "wisdom",
      "whyStart": "Continue the frame and first night already begun in Wisdom; this is the only long-running parallel read in the map.",
      "keywords": [
        "storytelling",
        "freedom",
        "frame story",
        "Burton"
      ]
    },
    {
      "id": "burton-sleeper-waker",
      "title": "The Sleeper and the Waker",
      "creator": "Traditional tale; translated by Richard F. Burton",
      "chapter": "5",
      "kind": "contained-story",
      "referenceStatus": "contained-work",
      "confidence": "high",
      "role": "Best source match for Gabriel's ‘Tale of Abu-l-Hasan, the Wag’; it locates the exact Burton volume behind Kafka's reading scene.",
      "sourceVersion": "Supplemental Nights, Volume 1 (1886), Project Gutenberg 3445",
      "sourceUrl": "https://www.gutenberg.org/cache/epub/3445/pg3445-images.html#link2H_4_0003",
      "evidenceUrl": "https://journalofthenights.blogspot.com/2009/09/",
      "rights": "Public domain in the United States; Project Gutenberg source.",
      "accessMode": "public-source",
      "canonicalSurface": "wisdom",
      "whyStart": "Read this first if the goal is the exact Burton trail named by the novel; stop after the tale rather than opening sixteen volumes.",
      "keywords": [
        "Abu al-Hasan",
        "Arabian Nights",
        "identity",
        "waking"
      ]
    },
    {
      "id": "plato-symposium",
      "title": "Symposium (also translated as The Banquet)",
      "creator": "Plato",
      "chapter": "5",
      "kind": "dialogue",
      "referenceStatus": "direct-title",
      "confidence": "high",
      "role": "Oshima uses Aristophanes' divided-human myth to talk about halves, solitude, sex, and the wish to become whole.",
      "sourceVersion": "Ancient Greek work; Perseus Greek/English edition",
      "sourceUrl": "https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.04.0090",
      "evidenceUrl": "https://www.supersummary.com/kafka-on-the-shore/prologue-chapter-6-summary/",
      "rights": "Ancient source text and early translations are public domain; modern translations remain edition-specific.",
      "accessMode": "public-source",
      "canonicalSurface": "wisdom",
      "whyStart": "Read only Aristophanes' speech, then ask whether the novel accepts or destabilizes the fantasy of a missing half.",
      "keywords": [
        "halves",
        "desire",
        "identity",
        "Aristophanes"
      ]
    },
    {
      "id": "kafka-castle",
      "title": "The Castle",
      "creator": "Franz Kafka",
      "chapter": "7",
      "kind": "novel",
      "referenceStatus": "direct-title",
      "confidence": "high",
      "role": "Part of Oshima's Kafka cluster: systems that stay legible enough to pursue but never fully yield.",
      "sourceVersion": "German original public domain; English translation rights vary",
      "sourceUrl": "https://www.gutenberg.org/ebooks/author/1735",
      "evidenceUrl": "https://www.supersummary.com/kafka-on-the-shore/chapters-7-12-summary/",
      "rights": "Original public domain in the United States; use only a rights-cleared translation.",
      "accessMode": "source-locator",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Kafka",
        "system",
        "access"
      ]
    },
    {
      "id": "kafka-trial",
      "title": "The Trial",
      "creator": "Franz Kafka",
      "chapter": "7",
      "kind": "novel",
      "referenceStatus": "direct-title",
      "confidence": "high",
      "role": "One of the works that makes Kafka's chosen name a method, not merely a literary pose.",
      "sourceVersion": "German original public domain; English translation rights vary",
      "sourceUrl": "https://www.gutenberg.org/ebooks/author/1735",
      "evidenceUrl": "https://www.supersummary.com/kafka-on-the-shore/chapters-7-12-summary/",
      "rights": "Original public domain in the United States; use only a rights-cleared translation.",
      "accessMode": "source-locator",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Kafka",
        "judgment",
        "fate"
      ]
    },
    {
      "id": "kafka-metamorphosis",
      "title": "The Metamorphosis",
      "creator": "Franz Kafka",
      "chapter": "7",
      "kind": "novella",
      "referenceStatus": "direct-title",
      "confidence": "high",
      "role": "The familiar work in Oshima's cluster; it establishes transformation without explaining it away.",
      "sourceVersion": "German original public domain; English translation rights vary",
      "sourceUrl": "https://www.gutenberg.org/ebooks/5200",
      "evidenceUrl": "https://www.supersummary.com/kafka-on-the-shore/chapters-7-12-summary/",
      "rights": "German original and some early English translations are public domain in the United States.",
      "accessMode": "public-source",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Kafka",
        "transformation",
        "family"
      ]
    },
    {
      "id": "kafka-penal-colony",
      "title": "In the Penal Colony",
      "creator": "Franz Kafka",
      "chapter": "7",
      "kind": "story",
      "referenceStatus": "direct-title",
      "confidence": "high",
      "role": "Kafka Tamura's favorite image is the punishment machine: law becomes literal inscription on the body.",
      "sourceVersion": "German original public domain; English translation rights vary",
      "sourceUrl": "https://www.gutenberg.org/ebooks/author/1735",
      "evidenceUrl": "https://www.supersummary.com/kafka-on-the-shore/chapters-7-12-summary/",
      "rights": "Original public domain in the United States; verify translation rights before reproducing.",
      "accessMode": "source-locator",
      "canonicalSurface": "wisdom",
      "keywords": [
        "machine",
        "law",
        "body",
        "Kafka"
      ]
    },
    {
      "id": "soseki-complete-works",
      "title": "Collected Works of Natsume Sōseki",
      "creator": "Natsume Sōseki",
      "chapter": "7",
      "kind": "collection",
      "referenceStatus": "direct-title",
      "confidence": "high",
      "role": "A library shelf and author-world that prepares the later close discussion of The Miner.",
      "sourceVersion": "Japanese originals; exact in-novel set not identified",
      "sourceUrl": "https://www.aozora.gr.jp/index_pages/person148.html",
      "evidenceUrl": "https://www.supersummary.com/kafka-on-the-shore/chapters-7-12-summary/",
      "rights": "Japanese originals public domain; modern English translations are edition-specific.",
      "accessMode": "public-source",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Soseki",
        "library",
        "Japan"
      ]
    },
    {
      "id": "genji-tanizaki",
      "title": "The Tale of Genji",
      "creator": "Murasaki Shikibu; modern-Japanese translation by Jun'ichirō Tanizaki",
      "chapter": "8, 23",
      "kind": "novel",
      "referenceStatus": "direct-title",
      "confidence": "high",
      "role": "The living-spirit model lets intense attachment act at a distance; Kafka later begins the work rather than merely hearing about it.",
      "sourceVersion": "Tanizaki modern-Japanese translation named in the novel",
      "sourceUrl": "https://www.chuko.co.jp/bunko/1991/07/201825.html",
      "evidenceUrl": "https://www.gradesaver.com/kafka-on-the-shore/study-guide/summary-chapters-20--29",
      "rights": "Ancient original public domain; Tanizaki and modern English translations are copyrighted. Link-only metadata here.",
      "accessMode": "metadata-only",
      "canonicalSurface": "wisdom",
      "note": "Do not substitute a different English translation while labeling it as the Tanizaki version named in the novel.",
      "keywords": [
        "living spirit",
        "memory",
        "jealousy",
        "Genji"
      ]
    },
    {
      "id": "soseki-miner",
      "title": "The Miner",
      "creator": "Natsume Sōseki",
      "chapter": "13",
      "kind": "novel",
      "referenceStatus": "direct-title",
      "confidence": "high",
      "role": "Oshima treats it as an anti-bildungsroman: a disturbing experience need not deliver tidy growth or a moral certificate.",
      "sourceVersion": "1908 Japanese original; modern English translations are copyrighted",
      "sourceUrl": "https://www.aozora.gr.jp/cards/000148/card774.html",
      "evidenceUrl": "https://www.supersummary.com/kafka-on-the-shore/chapters-13-16-summary/",
      "rights": "Japanese original public domain; modern English translation link/library only.",
      "accessMode": "source-locator",
      "canonicalSurface": "wisdom",
      "whyStart": "Read after Burton only if Jerry wants the novel's argument against compulsory self-improvement.",
      "keywords": [
        "experience",
        "growth",
        "miner",
        "Soseki"
      ]
    },
    {
      "id": "soseki-poppies",
      "title": "Poppies (The Poppy / Gubijinsō)",
      "creator": "Natsume Sōseki",
      "chapter": "13",
      "kind": "novel",
      "referenceStatus": "direct-title",
      "confidence": "high",
      "role": "One of the Sōseki works named around the contrast with The Miner.",
      "sourceVersion": "1907 Japanese original; English title varies by translation",
      "sourceUrl": "https://www.aozora.gr.jp/index_pages/person148.html",
      "evidenceUrl": "https://www.supersummary.com/kafka-on-the-shore/chapters-13-16-summary/",
      "rights": "Japanese original public domain; modern English translation rights vary.",
      "accessMode": "source-locator",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Soseki",
        "growth"
      ]
    },
    {
      "id": "soseki-sanshiro",
      "title": "Sanshirō",
      "creator": "Natsume Sōseki",
      "chapter": "13",
      "kind": "novel",
      "referenceStatus": "direct-title",
      "confidence": "high",
      "role": "Named as a more conventional formation novel against which The Miner can be read.",
      "sourceVersion": "1908 Japanese original",
      "sourceUrl": "https://www.aozora.gr.jp/index_pages/person148.html",
      "evidenceUrl": "https://www.supersummary.com/kafka-on-the-shore/chapters-13-16-summary/",
      "rights": "Japanese original public domain; modern English translation rights vary.",
      "accessMode": "source-locator",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Soseki",
        "formation"
      ]
    },
    {
      "id": "soseki-kokoro",
      "title": "Kokoro",
      "creator": "Natsume Sōseki",
      "chapter": "13",
      "kind": "novel",
      "referenceStatus": "direct-title",
      "confidence": "high",
      "role": "A named Sōseki comparator in the chapter's discussion of character and development.",
      "sourceVersion": "1914 Japanese original",
      "sourceUrl": "https://www.aozora.gr.jp/index_pages/person148.html",
      "evidenceUrl": "https://www.supersummary.com/kafka-on-the-shore/chapters-13-16-summary/",
      "rights": "Japanese original public domain; modern English translation rights vary.",
      "accessMode": "source-locator",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Soseki",
        "memory",
        "guilt"
      ]
    },
    {
      "id": "goethe-author",
      "title": "Goethe's ‘everything is a metaphor’ idea",
      "creator": "Johann Wolfgang von Goethe",
      "chapter": "13",
      "kind": "author-reference",
      "referenceStatus": "author-only",
      "confidence": "high",
      "role": "The author and idea are direct; scholars trace the line toward Faust Part II, but the novel does not safely name that title.",
      "sourceVersion": "Quotation provenance; work title unresolved in the novel",
      "sourceUrl": null,
      "evidenceUrl": "https://www.supersummary.com/kafka-on-the-shore/chapters-13-16-summary/",
      "rights": "Metadata and paraphrase only; do not promote Faust Part II to a direct named title.",
      "accessMode": "unresolved",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Goethe",
        "metaphor",
        "provenance"
      ]
    },
    {
      "id": "eichmann-trial-unknown",
      "title": "An unnamed book about Adolf Eichmann's trial",
      "creator": "Unidentified",
      "chapter": "15",
      "kind": "unresolved-book",
      "referenceStatus": "unresolved-title",
      "confidence": "high",
      "role": "A handwritten maxim inside the book turns imagination into responsibility; the novel does not identify the book's author or edition.",
      "sourceVersion": "Not identified in the novel",
      "sourceUrl": null,
      "evidenceUrl": "https://www.supersummary.com/kafka-on-the-shore/chapters-13-16-summary/",
      "rights": "Metadata only; do not silently resolve this to Hannah Arendt's Eichmann in Jerusalem.",
      "accessMode": "unresolved",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Eichmann",
        "responsibility",
        "imagination"
      ]
    },
    {
      "id": "yeats-responsibilities",
      "title": "Responsibilities",
      "creator": "W. B. Yeats",
      "chapter": "15",
      "kind": "poetry-collection",
      "referenceStatus": "paratext-source",
      "confidence": "medium",
      "role": "The maxim found inside the Eichmann-trial book traces to the epigraph of Yeats's 1914 collection, where it is attributed to an ‘Old Play.’",
      "sourceVersion": "1914 collection; Project Gutenberg 36865 uses the 1916 collected edition containing Responsibilities, 1912–1914",
      "sourceUrl": "https://www.gutenberg.org/ebooks/36865",
      "evidenceUrl": "https://www.supersummary.com/kafka-on-the-shore/chapters-13-16-summary/",
      "rights": "Early collection public domain in the United States; this map paraphrases its function and does not reproduce the line.",
      "accessMode": "public-source",
      "canonicalSurface": "wisdom",
      "note": "It is not a poem titled ‘Responsibilities.’",
      "keywords": [
        "Yeats",
        "responsibility",
        "dream"
      ]
    },
    {
      "id": "shakespeare-macbeth",
      "title": "Macbeth",
      "creator": "William Shakespeare",
      "chapter": "16",
      "kind": "play",
      "referenceStatus": "direct-title",
      "confidence": "high",
      "role": "Johnnie Walker invokes the play while fate, imagination, and enacted violence collapse into one another.",
      "sourceVersion": "Folger Shakespeare text",
      "sourceUrl": "https://www.folger.edu/explore/shakespeares-works/macbeth/read/",
      "evidenceUrl": "https://www.supersummary.com/kafka-on-the-shore/chapters-13-16-summary/",
      "rights": "Shakespeare public domain; Folger site terms govern its edition presentation.",
      "accessMode": "public-source",
      "canonicalSurface": "wisdom",
      "keywords": [
        "fate",
        "violence",
        "imagination"
      ]
    },
    {
      "id": "aeschylus-author",
      "title": "Aeschylus (play title not stated with confidence)",
      "creator": "Aeschylus",
      "chapter": "17",
      "kind": "author-reference",
      "referenceStatus": "author-only",
      "confidence": "high",
      "role": "Named in Oshima's Greek-tragedy discussion around Cassandra, knowledge, and powerlessness.",
      "sourceVersion": "Ancient Greek dramatic corpus",
      "sourceUrl": "https://www.perseus.tufts.edu/hopper/collections",
      "evidenceUrl": "https://edithhall.co.uk/wp-content/uploads/2023/03/ancient-greek-myth-in-world-fiction-proofs.pdf",
      "rights": "Ancient originals public domain; translation rights vary.",
      "accessMode": "source-locator",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Cassandra",
        "tragedy",
        "fate"
      ]
    },
    {
      "id": "euripides-author",
      "title": "Euripides (play title not stated with confidence)",
      "creator": "Euripides",
      "chapter": "17",
      "kind": "author-reference",
      "referenceStatus": "author-only",
      "confidence": "high",
      "role": "Named with Aeschylus as a route into Cassandra and the trap of foreknowledge without authority.",
      "sourceVersion": "Ancient Greek dramatic corpus",
      "sourceUrl": "https://www.perseus.tufts.edu/hopper/collections",
      "evidenceUrl": "https://edithhall.co.uk/wp-content/uploads/2023/03/ancient-greek-myth-in-world-fiction-proofs.pdf",
      "rights": "Ancient originals public domain; translation rights vary.",
      "accessMode": "source-locator",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Cassandra",
        "tragedy",
        "knowledge"
      ]
    },
    {
      "id": "shakespeare-romeo-juliet",
      "title": "Romeo and Juliet",
      "creator": "William Shakespeare",
      "chapter": "17",
      "kind": "play",
      "referenceStatus": "direct-title",
      "confidence": "high",
      "role": "A compact analogy inside the larger discussion of fate and tragic action.",
      "sourceVersion": "Folger Shakespeare text",
      "sourceUrl": "https://www.folger.edu/explore/shakespeares-works/romeo-and-juliet/read/",
      "evidenceUrl": "https://kots140.blogspot.com/2011/07/kafka-on-shore-texts-referenced.html",
      "rights": "Shakespeare public domain; Folger site terms govern its edition presentation.",
      "accessMode": "public-source",
      "canonicalSurface": "wisdom",
      "keywords": [
        "fate",
        "love",
        "tragedy"
      ]
    },
    {
      "id": "tolstoy-author",
      "title": "An unspecified work by Leo Tolstoy",
      "creator": "Leo Tolstoy",
      "chapter": "17",
      "kind": "author-reference",
      "referenceStatus": "author-only",
      "confidence": "high",
      "role": "Tolstoy is named, but the novel does not supply a work title secure enough for this map.",
      "sourceVersion": "Work unresolved",
      "sourceUrl": null,
      "evidenceUrl": "https://kots140.blogspot.com/2011/07/kafka-on-shore-texts-referenced.html",
      "rights": "Metadata only until the exact work is identified.",
      "accessMode": "unresolved",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Tolstoy"
      ]
    },
    {
      "id": "sophocles-electra",
      "title": "Electra",
      "creator": "Sophocles",
      "chapter": "19",
      "kind": "play",
      "referenceStatus": "direct-title",
      "confidence": "high",
      "role": "Oshima has reread and quotes the play; inherited violence and obligation do not become clean merely because they are ancient.",
      "sourceVersion": "Ancient Greek play; Perseus source",
      "sourceUrl": "https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.01.0187",
      "evidenceUrl": "https://edithhall.co.uk/wp-content/uploads/2023/03/ancient-greek-myth-in-world-fiction-proofs.pdf",
      "rights": "Ancient original public domain; translation rights vary.",
      "accessMode": "public-source",
      "canonicalSurface": "wisdom",
      "keywords": [
        "inheritance",
        "revenge",
        "tragedy"
      ]
    },
    {
      "id": "eliot-hollow-men",
      "title": "The Hollow Men",
      "creator": "T. S. Eliot",
      "chapter": "19",
      "kind": "poem",
      "referenceStatus": "direct-title",
      "confidence": "high",
      "role": "Used against empty, unimaginative moral language: interior vacancy can still produce consequence.",
      "sourceVersion": "1925 poem",
      "sourceUrl": "https://en.wikisource.org/wiki/The_Hollow_Men",
      "evidenceUrl": "https://www.supersummary.com/kafka-on-the-shore/chapters-17-20-summary/",
      "rights": "Public domain in the United States; link to the host rather than copying its presentation.",
      "accessMode": "public-source",
      "canonicalSurface": "wisdom",
      "keywords": [
        "emptiness",
        "responsibility",
        "imagination"
      ]
    },
    {
      "id": "aristotle-author",
      "title": "Aristotle's tragedy and rhetoric concepts",
      "creator": "Aristotle",
      "chapter": "19, 21",
      "kind": "author-reference",
      "referenceStatus": "author-only",
      "confidence": "high",
      "role": "Aristotle is credited for ideas about metaphor and tragedy; Rhetoric and Poetics are sensible source works but their titles are not secure direct quotations here.",
      "sourceVersion": "Ancient Greek philosophical corpus",
      "sourceUrl": "https://www.perseus.tufts.edu/hopper/collections",
      "evidenceUrl": "https://kots140.blogspot.com/2011/07/kafka-on-shore-texts-referenced.html",
      "rights": "Ancient originals public domain; translation rights vary.",
      "accessMode": "source-locator",
      "canonicalSurface": "wisdom",
      "keywords": [
        "tragedy",
        "metaphor",
        "Aristotle"
      ]
    },
    {
      "id": "sophocles-oedipus",
      "title": "Oedipus Rex",
      "creator": "Sophocles",
      "chapter": "21",
      "kind": "play",
      "referenceStatus": "direct-title",
      "confidence": "high",
      "role": "The novel's central fate structure: knowledge and virtue do not let Oedipus step outside the prophecy he is trying to defeat.",
      "sourceVersion": "Ancient Greek play; Perseus source",
      "sourceUrl": "https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.01.0191",
      "evidenceUrl": "https://edithhall.co.uk/wp-content/uploads/2023/03/ancient-greek-myth-in-world-fiction-proofs.pdf",
      "rights": "Ancient original public domain; translation rights vary.",
      "accessMode": "public-source",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Oedipus",
        "fate",
        "prophecy"
      ]
    },
    {
      "id": "akinari-ugetsu",
      "title": "Ugetsu Monogatari (Tales of Moonlight and Rain)",
      "creator": "Ueda Akinari",
      "chapter": "23",
      "kind": "story-collection",
      "referenceStatus": "direct-title",
      "confidence": "high",
      "role": "A Japanese counterweight to Genji: spirits can be driven by loyalty and promise, not only erotic jealousy.",
      "sourceVersion": "1776 Japanese collection",
      "sourceUrl": "https://www.aozora.gr.jp/index_pages/person127.html",
      "evidenceUrl": "https://ijellh.com/index.php/OJS/article/view/4980/4302",
      "rights": "Japanese original public domain; modern English translations are copyrighted.",
      "accessMode": "source-locator",
      "canonicalSurface": "wisdom",
      "keywords": [
        "spirit",
        "loyalty",
        "promise",
        "Ugetsu"
      ]
    },
    {
      "id": "akinari-chrysanthemum",
      "title": "The Chrysanthemum Pledge",
      "creator": "Ueda Akinari",
      "chapter": "23",
      "kind": "contained-story",
      "referenceStatus": "contained-work",
      "confidence": "high",
      "role": "The specific Ugetsu story under discussion; a promise survives bodily limits and foreshadows the novel's memory/spirit logic.",
      "sourceVersion": "Story within Ugetsu Monogatari",
      "sourceUrl": "https://www.aozora.gr.jp/index_pages/person127.html",
      "evidenceUrl": "https://ijellh.com/index.php/OJS/article/view/4980/4302",
      "rights": "Japanese original public domain; modern English translations are copyrighted.",
      "accessMode": "source-locator",
      "canonicalSurface": "wisdom",
      "whyStart": "Use this short tale after The Miner only if the living-spirit mechanism in chapter 23 is the live question; it is a bounded story, not another long parallel book.",
      "keywords": [
        "promise",
        "friendship",
        "spirit"
      ]
    },
    {
      "id": "saeki-lightning-interviews",
      "title": "Miss Saeki's unnamed book of lightning-strike interviews",
      "creator": "Miss Saeki (in-world author)",
      "chapter": "25",
      "kind": "in-novel-book",
      "referenceStatus": "in-novel-unresolved",
      "confidence": "high",
      "role": "The plot-relevant interview book includes Kafka's father and intensifies Kafka's hypothesis about Miss Saeki.",
      "sourceVersion": "Fictional in-world book; no external edition",
      "sourceUrl": null,
      "evidenceUrl": "https://kots140.blogspot.com/2011/07/kafka-on-shore-texts-referenced.html",
      "rights": "In-world identity and original analysis only; no fabricated outbound source.",
      "accessMode": "unresolved",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Miss Saeki",
        "lightning",
        "interviews",
        "Kafka's father"
      ]
    },
    {
      "id": "library-kagawa-legends",
      "title": "Legends of Kagawa Prefecture",
      "creator": "Unidentified / possibly in-novel title",
      "chapter": "26",
      "kind": "in-novel-book",
      "referenceStatus": "in-novel-unresolved",
      "confidence": "high",
      "role": "One of the local-library books Hoshino and Nakata use to turn place into a searchable trail.",
      "sourceVersion": "No verified real-world edition",
      "sourceUrl": null,
      "evidenceUrl": "https://kots140.blogspot.com/2011/07/kafka-on-shore-texts-referenced.html",
      "rights": "Identity unresolved; metadata only.",
      "accessMode": "unresolved",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Kagawa",
        "library",
        "local history"
      ]
    },
    {
      "id": "library-kobo-daishi",
      "title": "Legends of Kōbō Daishi in Shikoku",
      "creator": "Unidentified / possibly in-novel title",
      "chapter": "26",
      "kind": "in-novel-book",
      "referenceStatus": "in-novel-unresolved",
      "confidence": "high",
      "role": "A local legend book used during the practical search through Shikoku's memory.",
      "sourceVersion": "No verified real-world edition",
      "sourceUrl": null,
      "evidenceUrl": "https://kots140.blogspot.com/2011/07/kafka-on-shore-texts-referenced.html",
      "rights": "Identity unresolved; metadata only.",
      "accessMode": "unresolved",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Shikoku",
        "Kobo Daishi",
        "library"
      ]
    },
    {
      "id": "library-takamatsu-history",
      "title": "A History of Takamatsu",
      "creator": "Unidentified / possibly in-novel title",
      "chapter": "26",
      "kind": "in-novel-book",
      "referenceStatus": "in-novel-unresolved",
      "confidence": "high",
      "role": "Local history consulted as evidence rather than mystical interpretation.",
      "sourceVersion": "No verified real-world edition",
      "sourceUrl": null,
      "evidenceUrl": "https://kots140.blogspot.com/2011/07/kafka-on-shore-texts-referenced.html",
      "rights": "Identity unresolved; metadata only.",
      "accessMode": "unresolved",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Takamatsu",
        "history",
        "library"
      ]
    },
    {
      "id": "library-famous-stones",
      "title": "Famous Stones of Japan",
      "creator": "Unidentified / possibly in-novel title",
      "chapter": "26",
      "kind": "in-novel-book",
      "referenceStatus": "in-novel-unresolved",
      "confidence": "high",
      "role": "A deliberately literal research handle for the entrance stone.",
      "sourceVersion": "No verified real-world edition",
      "sourceUrl": null,
      "evidenceUrl": "https://kots140.blogspot.com/2011/07/kafka-on-shore-texts-referenced.html",
      "rights": "Identity unresolved; metadata only.",
      "accessMode": "unresolved",
      "canonicalSurface": "wisdom",
      "keywords": [
        "stone",
        "Japan",
        "library"
      ]
    },
    {
      "id": "library-cats-world",
      "title": "Cats of the World",
      "creator": "Unidentified / possibly in-novel title",
      "chapter": "26",
      "kind": "in-novel-book",
      "referenceStatus": "in-novel-unresolved",
      "confidence": "high",
      "role": "A comic and literal library choice that keeps Nakata's cat-world beside the larger metaphysical search.",
      "sourceVersion": "No verified real-world edition",
      "sourceUrl": null,
      "evidenceUrl": "https://kots140.blogspot.com/2011/07/kafka-on-shore-texts-referenced.html",
      "rights": "Identity unresolved; metadata only.",
      "accessMode": "unresolved",
      "canonicalSurface": "wisdom",
      "keywords": [
        "cats",
        "library",
        "Nakata"
      ]
    },
    {
      "id": "bergson-matter-memory",
      "title": "Matter and Memory",
      "creator": "Henri Bergson",
      "chapter": "28",
      "kind": "philosophy",
      "referenceStatus": "direct-title",
      "confidence": "high",
      "role": "The philosophy student supplies a vocabulary for body and spirit, present and past, and memory as more than stored representation.",
      "sourceVersion": "1911 Nancy Margaret Paul and W. Scott Palmer English translation",
      "sourceUrl": "https://openlibrary.org/books/OL7167762M/Matter_and_memory",
      "evidenceUrl": "https://kots140.blogspot.com/2011/07/kafka-on-shore-texts-referenced.html",
      "rights": "Original and 1911 English translation public domain in the United States.",
      "accessMode": "public-source",
      "canonicalSurface": "wisdom",
      "keywords": [
        "memory",
        "body",
        "spirit",
        "Bergson"
      ]
    },
    {
      "id": "hegel-author",
      "title": "An unspecified work by G. W. F. Hegel",
      "creator": "G. W. F. Hegel",
      "chapter": "28",
      "kind": "author-reference",
      "referenceStatus": "author-only",
      "confidence": "high",
      "role": "Hegel is quoted or paraphrased, but the novel does not name a secure title.",
      "sourceVersion": "Work unresolved",
      "sourceUrl": null,
      "evidenceUrl": "https://www.supersummary.com/kafka-on-the-shore/chapters-25-28-summary/",
      "rights": "Metadata only until the exact work is identified.",
      "accessMode": "unresolved",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Hegel",
        "philosophy"
      ]
    },
    {
      "id": "chekhov-gun-principle",
      "title": "Chekhov's gun principle",
      "creator": "Anton Chekhov",
      "chapter": "30",
      "kind": "author-reference",
      "referenceStatus": "author-only",
      "confidence": "high",
      "role": "The pistol principle is applied to the entrance stone: a conspicuous element creates an expectation that it will act.",
      "sourceVersion": "Author/concept reference; no Chekhov work title safely named",
      "sourceUrl": null,
      "evidenceUrl": "https://kots140.blogspot.com/2011/07/kafka-on-shore-texts-referenced.html",
      "rights": "Metadata and paraphrase only; Uncle Vanya remains an inferred source example.",
      "accessMode": "unresolved",
      "canonicalSurface": "wisdom",
      "keywords": [
        "entrance stone",
        "setup",
        "Chekhov"
      ]
    },
    {
      "id": "lorca-author",
      "title": "Federico García Lorca (work not specified)",
      "creator": "Federico García Lorca",
      "chapter": "31",
      "kind": "author-reference",
      "referenceStatus": "author-only",
      "confidence": "high",
      "role": "Named in the Spanish Civil War context rather than assigned a specific book.",
      "sourceVersion": "Work unresolved",
      "sourceUrl": null,
      "evidenceUrl": "https://kots140.blogspot.com/2011/07/kafka-on-shore-texts-referenced.html",
      "rights": "Metadata only; translation and edition rights vary.",
      "accessMode": "unresolved",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Spain",
        "civil war",
        "Lorca"
      ]
    },
    {
      "id": "hemingway-author",
      "title": "Ernest Hemingway (work not specified)",
      "creator": "Ernest Hemingway",
      "chapter": "31",
      "kind": "author-reference",
      "referenceStatus": "author-only",
      "confidence": "high",
      "role": "Named in the Spanish Civil War context; no specific title is made canonical here.",
      "sourceVersion": "Work unresolved",
      "sourceUrl": null,
      "evidenceUrl": "https://kots140.blogspot.com/2011/07/kafka-on-shore-texts-referenced.html",
      "rights": "Metadata only; many works remain copyrighted in relevant jurisdictions.",
      "accessMode": "unresolved",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Spain",
        "civil war",
        "Hemingway"
      ]
    },
    {
      "id": "dickens-author",
      "title": "Charles Dickens (work not specified)",
      "creator": "Charles Dickens",
      "chapter": "32",
      "kind": "author-reference",
      "referenceStatus": "author-only",
      "confidence": "high",
      "role": "A visual comparison for the buildings Nakata observes outside the Takamatsu hotel, not a reading assignment.",
      "sourceVersion": "Work unresolved",
      "sourceUrl": null,
      "evidenceUrl": "https://kots140.blogspot.com/2011/07/kafka-on-shore-texts-referenced.html",
      "rights": "Metadata only until the exact work is identified.",
      "accessMode": "unresolved",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Dickens",
        "buildings",
        "comparison"
      ]
    },
    {
      "id": "aladdin-allusion",
      "title": "Aladdin",
      "creator": "Traditional tale transmitted through Antoine Galland's French Nights",
      "chapter": "32",
      "kind": "story",
      "referenceStatus": "explicit-allusion",
      "confidence": "high",
      "role": "An Arabian Nights allusion that extends the novel's bottle, wish, and released-force imagery.",
      "sourceVersion": "Galland-associated orphan tale; not in the earliest surviving Arabic manuscript corpus",
      "sourceUrl": "https://www.gutenberg.org/ebooks/128",
      "evidenceUrl": "https://kots140.blogspot.com/2011/07/kafka-on-shore-texts-referenced.html",
      "rights": "Early tellings and translations public domain; edition histories differ.",
      "accessMode": "public-source",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Aladdin",
        "Nights",
        "bottle",
        "wish"
      ]
    },
    {
      "id": "grimm-frog-prince",
      "title": "The Frog Prince",
      "creator": "Jacob and Wilhelm Grimm",
      "chapter": "32",
      "kind": "fairy-tale",
      "referenceStatus": "explicit-allusion",
      "confidence": "high",
      "role": "A familiar fairy-tale comparison, not a recommendation to begin a Grimm sequence.",
      "sourceVersion": "Grimm tale; early translations public domain",
      "sourceUrl": "https://www.gutenberg.org/ebooks/2591",
      "evidenceUrl": "https://kots140.blogspot.com/2011/07/kafka-on-shore-texts-referenced.html",
      "rights": "Original and early translations public domain in the United States.",
      "accessMode": "public-source",
      "canonicalSurface": "wisdom",
      "keywords": [
        "fairy tale",
        "transformation",
        "Grimm"
      ]
    },
    {
      "id": "rousseau-fence-concept",
      "title": "Rousseau's fence and civilization idea",
      "creator": "Jean-Jacques Rousseau",
      "chapter": "33",
      "kind": "author-reference",
      "referenceStatus": "author-only",
      "confidence": "high",
      "role": "The idea about fences, ownership, and civilization is direct; the Discourse is likely provenance, not a securely named title.",
      "sourceVersion": "Author/concept reference; exact title unresolved in the novel",
      "sourceUrl": null,
      "evidenceUrl": "https://kots140.blogspot.com/2011/07/kafka-on-shore-texts-referenced.html",
      "rights": "Metadata and paraphrase only; do not promote the Discourse to a direct named work.",
      "accessMode": "unresolved",
      "canonicalSurface": "wisdom",
      "keywords": [
        "fence",
        "property",
        "society",
        "Rousseau"
      ]
    },
    {
      "id": "napoleon-1812-unknown",
      "title": "An unnamed book about Napoleon's 1812 invasion of Russia",
      "creator": "Unidentified",
      "chapter": "37",
      "kind": "unresolved-book",
      "referenceStatus": "unresolved-title",
      "confidence": "high",
      "role": "A historical book is present, but neither author nor title is supplied.",
      "sourceVersion": "Not identified in the novel",
      "sourceUrl": null,
      "evidenceUrl": "https://kots140.blogspot.com/2011/07/kafka-on-shore-texts-referenced.html",
      "rights": "Metadata only; do not invent an edition.",
      "accessMode": "unresolved",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Napoleon",
        "Russia",
        "1812"
      ]
    },
    {
      "id": "grimm-hansel-gretel",
      "title": "Hansel and Gretel",
      "creator": "Jacob and Wilhelm Grimm",
      "chapter": "37",
      "kind": "fairy-tale",
      "referenceStatus": "explicit-allusion",
      "confidence": "high",
      "role": "A forest, abandonment, and homeward-path allusion inside the novel's own dangerous woods.",
      "sourceVersion": "Grimm tale; early translations public domain",
      "sourceUrl": "https://www.gutenberg.org/ebooks/2591",
      "evidenceUrl": "https://kots140.blogspot.com/2011/07/kafka-on-shore-texts-referenced.html",
      "rights": "Original and early translations public domain in the United States.",
      "accessMode": "public-source",
      "canonicalSurface": "wisdom",
      "keywords": [
        "forest",
        "abandonment",
        "home",
        "Grimm"
      ]
    },
    {
      "id": "beethoven-generation",
      "title": "Beethoven and His Generation",
      "creator": "Unidentified / possibly in-novel title",
      "chapter": "40",
      "kind": "in-novel-book",
      "referenceStatus": "in-novel-unresolved",
      "confidence": "high",
      "role": "Hoshino's library reading makes listening historical and relational rather than a vague ‘classical music’ upgrade.",
      "sourceVersion": "No verified real-world bibliographic identity",
      "sourceUrl": null,
      "evidenceUrl": "https://www.gradesaver.com/kafka-on-the-shore/study-guide/summary-chapters-40--49",
      "rights": "Identity unresolved; metadata only.",
      "accessMode": "unresolved",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Beethoven",
        "listening",
        "Hoshino"
      ]
    },
    {
      "id": "berlioz-hamlet-remark",
      "title": "Hector Berlioz's remark on encountering Hamlet",
      "creator": "Hector Berlioz",
      "chapter": "40",
      "kind": "author-reference",
      "referenceStatus": "paratext-source",
      "confidence": "high",
      "role": "The quotation frames art as a before-and-after encounter for Hoshino; it is provenance for Hamlet, not another book title.",
      "sourceVersion": "Composer-level quotation; exact printed source not established here",
      "sourceUrl": null,
      "evidenceUrl": "https://www.gradesaver.com/kafka-on-the-shore/study-guide/summary-chapters-40--49",
      "rights": "Metadata and paraphrase only; exact source unresolved.",
      "accessMode": "unresolved",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Berlioz",
        "Hamlet",
        "encounter"
      ]
    },
    {
      "id": "shakespeare-hamlet",
      "title": "Hamlet",
      "creator": "William Shakespeare",
      "chapter": "40",
      "kind": "play",
      "referenceStatus": "direct-title",
      "confidence": "high",
      "role": "Reached through Berlioz: one complete encounter enlarges Hoshino's inner world rather than merely giving him cultural facts.",
      "sourceVersion": "Folger Shakespeare text",
      "sourceUrl": "https://www.folger.edu/explore/shakespeares-works/hamlet/read/",
      "evidenceUrl": "https://www.gradesaver.com/kafka-on-the-shore/study-guide/summary-chapters-40--49",
      "rights": "Shakespeare public domain; Folger site terms govern its edition presentation.",
      "accessMode": "public-source",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Hamlet",
        "Berlioz",
        "listening",
        "Hoshino"
      ]
    },
    {
      "id": "kafka-on-shore-inworld-artifacts",
      "title": "‘Kafka on the Shore’ song, lyrics, sheet music, LP, and painting",
      "creator": "Miss Saeki (in-world artifacts)",
      "chapter": "23",
      "kind": "in-world-text-cluster",
      "referenceStatus": "in-novel-unresolved",
      "confidence": "high",
      "role": "A single fictional artifact cluster binds text, music, image, memory, and the novel's title; it is not a real record or book to source externally.",
      "sourceVersion": "Fictional in-world artifacts",
      "sourceUrl": null,
      "evidenceUrl": "https://www.gradesaver.com/kafka-on-the-shore/study-guide/summary-chapters-20--29",
      "rights": "Metadata and original analysis only; no novel lyrics or image reproduction.",
      "accessMode": "unresolved",
      "canonicalSurface": "wisdom",
      "keywords": [
        "Miss Saeki",
        "song",
        "lyrics",
        "painting",
        "memory"
      ]
    }
  ],
  "excludedOrInferred": [
    {
      "title": "Agamemnon",
      "reason": "A useful Aeschylus/Cassandra start and present in popular reference lists, but the defensible novel evidence names Aeschylus rather than securely naming this play."
    },
    {
      "title": "The Trojan Women",
      "reason": "A useful Euripides/Cassandra start and present in popular reference lists, but the sourced passage does not securely supply the play title."
    },
    {
      "title": "Rhetoric",
      "reason": "Aristotle's rhetoric/metaphor concept is direct; the title is not secure enough to label direct."
    },
    {
      "title": "Poetics",
      "reason": "Aristotle's tragedy principle is direct; the exact treatise title is an inference."
    },
    {
      "title": "Faust Part II",
      "reason": "Useful provenance for Goethe's metaphor line, but the novel does not safely name the title."
    },
    {
      "title": "Uncle Vanya",
      "reason": "Popular lists upgrade Chekhov's gun principle to this play; the title is not securely named."
    },
    {
      "title": "Discourse on the Origin of Inequality",
      "reason": "Likely provenance for Rousseau's fence/civilization idea, not a securely named title in the novel."
    },
    {
      "title": "Eichmann in Jerusalem",
      "reason": "The novel's Eichmann-trial book is unnamed. Hannah Arendt is plausible, not proven."
    },
    {
      "title": "Invisible Man",
      "reason": "A later blog comment upgrades a generic ‘invisible man’ phrase to Ralph Ellison; no independent chapter evidence cleared the bar."
    },
    {
      "title": "Walden / Huckleberry Finn / I Am a Cat / Forrest Gump / Being There",
      "reason": "These are common thematic or critical parallels, not direct book-reference facts in the verified inventory."
    }
  ],
  "dataSha256": "dd2747471109bb59123b61ad2788478881920616d3339f95b3843fa532ffcff3"
};
