window.ESSAY_TEXT = {
  "id": "james-laws-of-habit",
  "title": "The Laws of Habit (Talks to Teachers, VIII)",
  "titleOriginal": null,
  "author": "William James",
  "authorNative": null,
  "year": 1899,
  "language": "en",
  "kind": "chapter",
  "why": "Already named in wisdom-texts as the fallback non-Seneca artifact: when the motive fades, what structure keeps action alive? This is the practical habit/attention/will lens from the writing-thinker study plan.",
  "themes": [
    "habit",
    "will",
    "practice"
  ],
  "rightsNote": "Published 1899; US public domain.",
  "sourceLabel": "Project Gutenberg eBook 16287",
  "sourcePage": "https://www.gutenberg.org/ebooks/16287",
  "provenance": "fetched (scripts/build_essays_sources.py; local mirror: 16287-8.txt)",
  "generated": "2026-07-11",
  "paragraphs": [
    "THE LAWS OF HABIT",
    "It is very important that teachers should realize the importance of\nhabit, and psychology helps us greatly at this point. We speak, it is\ntrue, of good habits and of bad habits; but, when people use the word\n'habit,' in the majority of instances it is a bad habit which they\nhave in mind. They talk of the smoking-habit and the swearing-habit\nand the drinking-habit, but not of the abstention-habit or the\nmoderation-habit or the courage-habit. But the fact is that our\nvirtues are habits as much as our vices. All our life, so far as it\nhas definite form, is but a mass of habits,--practical, emotional, and\nintellectual,--systematically organized for our weal or woe, and\nbearing us irresistibly toward our destiny, whatever the latter may be.",
    "Since pupils can understand this at a comparatively early age, and since\nto understand it contributes in no small measure to their feeling of\nresponsibility, it would be well if the teacher were able himself to\ntalk to them of the philosophy of habit in some such abstract terms as I\nam now about to talk of it to you.",
    "I believe that we are subject to the law of habit in consequence of the\nfact that we have bodies. The plasticity of the living matter of our\nnervous system, in short, is the reason why we do a thing with\ndifficulty the first time, but soon do it more and more easily, and\nfinally, with sufficient practice, do it semi-mechanically, or with\nhardly any consciousness at all. Our nervous systems have (in Dr.\nCarpenter's words) _grown_ to the way in which they have been exercised,\njust as a sheet of paper or a coat, once creased or folded, tends to\nfall forever afterward into the same identical folds.",
    "Habit is thus a second nature, or rather, as the Duke of Wellington\nsaid, it is 'ten times nature,'--at any rate as regards its importance\nin adult life; for the acquired habits of our training have by that time\ninhibited or strangled most of the natural impulsive tendencies which\nwere originally there. Ninety-nine hundredths or, possibly, nine hundred\nand ninety-nine thousandths of our activity is purely automatic and\nhabitual, from our rising in the morning to our lying down each night.\nOur dressing and undressing, our eating and drinking, our greetings and\npartings, our hat-raisings and giving way for ladies to precede, nay,\neven most of the forms of our common speech, are things of a type so\nfixed by repetition as almost to be classed as reflex actions. To each\nsort of impression we have an automatic, ready-made response. My very\nwords to you now are an example of what I mean; for having already\nlectured upon habit and printed a chapter about it in a book, and read\nthe latter when in print, I find my tongue inevitably falling into its\nold phrases and repeating almost literally what I said before.",
    "So far as we are thus mere bundles of habit, we are stereotyped\ncreatures, imitators and copiers of our past selves. And since this,\nunder any circumstances, is what we always tend to become, it follows\nfirst of all that the teacher's prime concern should be to ingrain into\nthe pupil that assortment of habits that shall be most useful to him\nthroughout life. Education is for behavior, and habits are the stuff of\nwhich behavior consists.",
    "To quote my earlier book directly, the great thing in all education is\nto _make our nervous system our ally instead of our enemy_. It is to\nfund and capitalize our acquisitions, and live at ease upon the\ninterest of the fund. _For this we must make automatic and habitual, as\nearly as possible, as many useful actions as we can_, and as carefully\nguard against the growing into ways that are likely to be\ndisadvantageous. The more of the details of our daily life we can hand\nover to the effortless custody of automatism, the more our higher powers\nof mind will be set free for their own proper work. There is no more\nmiserable human being than one in whom nothing is habitual but\nindecision, and for whom the lighting of every cigar, the drinking of\nevery cup, the time of rising and going to bed every day, and the\nbeginning of every bit of work are subjects of express volitional\ndeliberation. Full half the time of such a man goes to the deciding or\nregretting of matters which ought to be so ingrained in him as\npractically not to exist for his consciousness at all. If there be such\ndaily duties not yet ingrained in any one of my hearers, let him begin\nthis very hour to set the matter right.",
    "In Professor Bain's chapter on 'The Moral Habits' there are some\nadmirable practical remarks laid down. Two great maxims emerge from the\ntreatment. The first is that in the acquisition of a new habit, or the\nleaving off of an old one, we must take care to _launch ourselves with\nas strong and decided an initiative as possible_. Accumulate all the\npossible circumstances which shall reinforce the right motives; put\nyourself assiduously in conditions that encourage the new way; make\nengagements incompatible with the old; take a public pledge, if the case\nallows; in short, envelope your resolution with every aid you know. This\nwill give your new beginning such a momentum that the temptation to\nbreak down will not occur as soon as it otherwise might; and every day\nduring which a breakdown is postponed adds to the chances of its not\noccurring at all.",
    "I remember long ago reading in an Austrian paper the advertisement of a\ncertain Rudolph Somebody, who promised fifty gulden reward to any one\nwho after that date should find him at the wine-shop of Ambrosius\nSo-and-so. 'This I do,' the advertisement continued, 'in consequence of\na promise which I have made my wife.' With such a wife, and such an\nunderstanding of the way in which to start new habits, it would be safe\nto stake one's money on Rudolph's ultimate success.",
    "The second maxim is, _Never suffer an exception to occur till the new\nhabit is securely rooted in your life_. Each lapse is like the letting\nfall of a ball of string which one is carefully winding up: a single\nslip undoes more than a great many turns will wind again. Continuity of\ntraining is the great means of making the nervous system act infallibly\nright. As Professor Bain says:--",
    "\"The peculiarity of the moral habits, contradistinguishing them from the\nintellectual acquisitions, is the presence of two hostile powers, one to\nbe gradually raised into the ascendant over the other. It is necessary\nabove all things, in such a situation, never to lose a battle. Every\ngain on the wrong side undoes the effect of many conquests on the right.\nThe essential precaution, therefore, is so to regulate the two opposing\npowers that the one may have a series of uninterrupted successes, until\nrepetition has fortified it to such a degree as to enable it to cope\nwith the opposition, under any circumstances. This is the theoretically\nbest career of mental progress.\"",
    "A third maxim may be added to the preceding pair: _Seize the very first\npossible opportunity to act on every resolution you make, and on every\nemotional prompting you may experience in the direction of the habits\nyou aspire to gain._ It is not in the moment of their forming, but in\nthe moment of their producing motor effects, that resolves and\naspirations communicate the new 'set' to the brain.",
    "No matter how full a reservoir of maxims one may possess, and no matter\nhow good one's sentiments may be, if one have not taken advantage of\nevery concrete opportunity to act, one's character may remain entirely\nunaffected for the better. With good intentions, hell proverbially is\npaved. This is an obvious consequence of the principles I have laid\ndown. A 'character,' as J.S. Mill says, 'is a completely fashioned\nwill'; and a will, in the sense in which he means it, is an aggregate of\ntendencies to act in a firm and prompt and definite way upon all the\nprincipal emergencies of life. A tendency to act only becomes\neffectively ingrained in us in proportion to the uninterrupted frequency\nwith which the actions actually occur, and the brain 'grows' to their\nuse. When a resolve or a fine glow of feeling is allowed to evaporate\nwithout bearing practical fruit, it is worse than a chance lost: it\nworks so as positively to hinder future resolutions and emotions from\ntaking the normal path of discharge. There is no more contemptible type\nof human character than that of the nerveless sentimentalist and\ndreamer, who spends his life in a weltering sea of sensibility, but\nnever does a concrete manly deed.",
    "This leads to a fourth maxim. _Don't preach too much to your pupils or\nabound in good talk in the abstract_. Lie in wait rather for the\npractical opportunities, be prompt to seize those as they pass, and thus\nat one operation get your pupils both to think, to feel, and to do. The\nstrokes of _behavior_ are what give the new set to the character, and\nwork the good habits into its organic tissue. Preaching and talking too\nsoon become an ineffectual bore.",
    "* * * * *",
    "There is a passage in Darwin's short autobiography which has been often\nquoted, and which, for the sake of its bearing on our subject of habit,\nI must now quote again. Darwin says: \"Up to the age of thirty or beyond\nit, poetry of many kinds gave me great pleasure; and even as a schoolboy\nI took intense delight in Shakespeare, especially in the historical\nplays. I have also said that pictures formerly gave me considerable, and\nmusic very great delight. But now for many years I cannot endure to read\na line of poetry. I have tried lately to read Shakespeare, and found it\nso intolerably dull that it nauseated me. I have also almost lost my\ntaste for pictures or music.... My mind seems to have become a kind of\nmachine for grinding general laws out of large collections of facts; but\nwhy this should have caused the atrophy of that part of the brain alone,\non which the higher tastes depend, I cannot conceive.... If I had to\nlive my life again, I would have made a rule to read some poetry and\nlisten to some music at least once every week; for perhaps the parts of\nmy brain now atrophied would thus have been kept alive through use. The\nloss of these tastes is a loss of happiness, and may possibly be\ninjurious to the intellect, and more probably to the moral character, by\nenfeebling the emotional part of our nature.\"",
    "We all intend when young to be all that may become a man, before the\ndestroyer cuts us down. We wish and expect to enjoy poetry always, to\ngrow more and more intelligent about pictures and music, to keep in\ntouch with spiritual and religious ideas, and even not to let the\ngreater philosophic thoughts of our time develop quite beyond our view.\nWe mean all this in youth, I say; and yet in how many middle-aged men\nand women is such an honest and sanguine expectation fulfilled? Surely,\nin comparatively few; and the laws of habit show us why. Some interest\nin each of these things arises in everybody at the proper age; but, if\nnot persistently fed with the appropriate matter, instead of growing\ninto a powerful and necessary habit, it atrophies and dies, choked by\nthe rival interests to which the daily food is given. We make ourselves\ninto Darwins in this negative respect by persistently ignoring the\nessential practical conditions of our case. We say abstractly: \"I mean\nto enjoy poetry, and to absorb a lot of it, of course. I fully intend to\nkeep up my love of music, to read the books that shall give new turns to\nthe thought of my time, to keep my higher spiritual side alive, etc.\"\nBut we do not attack these things concretely, and we do not begin\n_to-day. _We forget that every good that is worth possessing must be\npaid for in strokes of daily effort. We postpone and postpone, until\nthose smiling possibilities are dead. Whereas ten minutes a day of\npoetry, of spiritual reading or meditation, and an hour or two a week at\nmusic, pictures, or philosophy, provided we began _now_ and suffered no\nremission, would infallibly give us in due time the fulness of all we\ndesire. By neglecting the necessary concrete labor, by sparing\nourselves the little daily tax, we are positively digging the graves of\nour higher possibilities. This is a point concerning which you teachers\nmight well give a little timely information to your older and more\naspiring pupils.",
    "According as a function receives daily exercise or not, the man becomes\na different kind of being in later life. We have lately had a number of\naccomplished Hindoo visitors at Cambridge, who talked freely of life and\nphilosophy. More than one of them has confided to me that the sight of\nour faces, all contracted as they are with the habitual American\nover-intensity and anxiety of expression, and our ungraceful and\ndistorted attitudes when sitting, made on him a very painful impression.\n\"I do not see,\" said one, \"how it is possible for you to live as you do,\nwithout a single minute in your day deliberately given to tranquillity\nand meditation. It is an invariable part of our Hindoo life to retire\nfor at least half an hour daily into silence, to relax our muscles,\ngovern our breathing, and meditate on eternal things. Every Hindoo child\nis trained to this from a very early age.\" The good fruits of such a\ndiscipline were obvious in the physical repose and lack of tension, and\nthe wonderful smoothness and calmness of facial expression, and\nimperturbability of manner of these Orientals. I felt that my countrymen\nwere depriving themselves of an essential grace of character. How many\nAmerican children ever hear it said by parent or teacher, that they\nshould moderate their piercing voices, that they should relax their\nunused muscles, and as far as possible, when sitting, sit quite still?\nNot one in a thousand, not one in five thousand! Yet, from its reflex\ninfluence on the inner mental states, this ceaseless over-tension,\nover-motion, and over-expression are working on us grievous national\nharm.",
    "I beg you teachers to think a little seriously of this matter. Perhaps\nyou can help our rising generation of Americans toward the beginning of\na better set of personal ideals.[B]",
    "[B] See the Address on the Gospel of Relaxation, later in\nthis volume.",
    "* * * * *",
    "To go back now to our general maxims, I may at last, as a fifth and\nfinal practical maxim about habits, offer something like this: _Keep the\nfaculty of effort alive in you by a little gratuitous exercise every\nday._ That is, be systematically heroic in little unnecessary points, do\nevery day or two something for no other reason than its difficulty, so\nthat, when the hour of dire need draws nigh, it may find you not\nunnerved and untrained to stand the test. Asceticism of this sort is\nlike the insurance which a man pays on his house and goods. The tax does\nhim no good at the time, and possibly may never bring him a return. But,\nif the fire _does_ come, his having paid it will be his salvation from\nruin. So with the man who has daily inured himself to habits of\nconcentrated attention, energetic volition, and self-denial in\nunnecessary things. He will stand like a tower when everything rocks\naround him, and his softer fellow-mortals are winnowed like chaff in the\nblast.",
    "* * * * *",
    "I have been accused, when talking of the subject of habit, of making old\nhabits appear so strong that the acquiring of new ones, and particularly\nanything like a sudden reform or conversion, would be made impossible by\nmy doctrine. Of course, this would suffice to condemn the latter; for\nsudden conversions, however infrequent they may be, unquestionably do\noccur. But there is no incompatibility between the general laws I have\nlaid down and the most startling sudden alterations in the way of\ncharacter. New habits _can_ be launched, I have expressly said, on\ncondition of there being new stimuli and new excitements. Now life\nabounds in these, and sometimes they are such critical and revolutionary\nexperiences that they change a man's whole scale of values and system of\nideas. In such cases, the old order of his habits will be ruptured; and,\nif the new motives are lasting, new habits will be formed, and build up\nin him a new or regenerate 'nature.'",
    "All this kind of fact I fully allow. But the general laws of habit are\nno wise altered thereby, and the physiological study of mental\nconditions still remains on the whole the most powerful ally of\nhortatory ethics. The hell to be endured hereafter, of which theology\ntells, is no worse than the hell we make for ourselves in this world by\nhabitually fashioning our characters in the wrong way. Could the young\nbut realize how soon they will become mere walking bundles of habits,\nthey would give more heed to their conduct while in the plastic state.\nWe are spinning our own fates, good or evil, and never to be undone.\nEvery smallest stroke of virtue or of vice leaves its never-so-little\nscar. The drunken Rip Van Winkle, in Jefferson's play, excuses himself\nfor every fresh dereliction by saying, \"I won't count this time!\" Well,\nhe may not count it, and a kind Heaven may not count it; but it is being\ncounted none the less. Down among his nerve-cells and fibres the\nmolecules are counting it, registering and storing it up to be used\nagainst him when the next temptation comes. Nothing we ever do is, in\nstrict scientific literalness, wiped out.",
    "Of course, this has its good side as well as its bad one. As we become\npermanent drunkards by so many separate drinks, so we become saints in\nthe moral, and authorities and experts in the practical and scientific\nspheres, by so many separate acts and hours of work. Let no youth have\nany anxiety about the upshot of his education, whatever the line of it\nmay be. If he keep faithfully busy each hour of the working day, he may\nsafely leave the final result to itself. He can with perfect certainty\ncount on waking up some fine morning to find himself one of the\ncompetent ones of his generation, in whatever pursuit he may have\nsingled out. Silently, between all the details of his business, the\n_power of judging_ in all that class of matter will have built itself up\nwithin him as a possession that will never pass away. Young people\nshould know this truth in advance. The ignorance of it has probably\nengendered more discouragement and faint-heartedness in youths embarking\non arduous careers than all other causes put together."
  ],
  "guideIntro": [
    "James treats habit as the mechanism that converts repeated acts into character. The practical advice is deliberately physical and immediate: make the nervous system an ally before intention has to fight every action from scratch."
  ],
  "notes": {
    "7": "The first rule—launch a new habit with strong initiative and favorable circumstances—recognizes that beginnings need more energy than maintenance.",
    "17": "James's warning about youthful aspirations is not that personality freezes at thirty. It is that unused capacities become harder to summon when daily life repeatedly votes against them.",
    "26": "The closing symmetry matters: repetition can make drunkards or experts, vice or sainthood. Habit is morally neutral infrastructure; direction comes from the acts being automated."
  },
  "audio": {}
};
